package storage

import (
	"fmt"
	"sort"
	"strings"
)

// MountEntry is one declarative mount that must survive reboots via a
// generated systemd mount unit.
type MountEntry struct {
	Kind      string `json:"kind"`      // "disk" or "pool"
	TargetID  string `json:"targetId"`  // stable disk identity or pool name
	MountPath string `json:"mountPath"` // canonical /srv/disks/<id> or /srv/pools/<name>
	FSType    string `json:"fstype"`    // ext4, xfs, or fuse.mergerfs
	Source    string `json:"source"`    // UUID=<filesystem uuid> or colon-joined branch paths
	Options   string `json:"options"`
	Enabled   bool   `json:"enabled"`
}

const (
	DiskMountOptions  = "defaults,nofail"
	PoolMountOptions  = "defaults,allow_other,use_ino,category.create=mfs"
	UnitDirectoryHint = "generated by lumonasd; edit storage through the LumoNAS API"
)

// NormalizeMountEntries sorts and validates a desired mount state.
func NormalizeMountEntries(entries []MountEntry) ([]MountEntry, error) {
	result := make([]MountEntry, 0, len(entries))
	seen := make(map[string]bool, len(entries))
	for _, entry := range entries {
		if entry.Kind != "disk" && entry.Kind != "pool" {
			return nil, fmt.Errorf("mount kind %q is invalid", entry.Kind)
		}
		if err := validateMountEntry(entry); err != nil {
			return nil, err
		}
		if seen[entry.MountPath] {
			return nil, fmt.Errorf("mount path %q is duplicated", entry.MountPath)
		}
		seen[entry.MountPath] = true
		result = append(result, entry)
	}
	sort.Slice(result, func(i, j int) bool { return result[i].MountPath < result[j].MountPath })
	return result, nil
}

func validateMountEntry(entry MountEntry) error {
	switch entry.Kind {
	case "disk":
		if entry.TargetID == "" {
			return fmt.Errorf("disk mount %q requires a stable disk identity", entry.MountPath)
		}
		if entry.MountPath != DiskBranchPath(entry.TargetID) {
			return fmt.Errorf("disk mount path %q is not the canonical branch path", entry.MountPath)
		}
		if entry.FSType != "ext4" && entry.FSType != "xfs" {
			return fmt.Errorf("disk mount filesystem %q is not allow-listed", entry.FSType)
		}
		if !strings.HasPrefix(entry.Source, "UUID=") || len(entry.Source) < 6 {
			return fmt.Errorf("disk mount %q requires a UUID= source", entry.MountPath)
		}
	case "pool":
		if entry.TargetID == "" {
			return fmt.Errorf("pool mount %q requires a pool name", entry.MountPath)
		}
		if entry.MountPath != "/srv/pools/"+entry.TargetID {
			return fmt.Errorf("pool mount path %q is not canonical", entry.MountPath)
		}
		if entry.FSType != "fuse.mergerfs" {
			return fmt.Errorf("pool mount filesystem %q must be fuse.mergerfs", entry.FSType)
		}
		for _, branch := range strings.Split(entry.Source, ":") {
			if !safeBranchPath(branch) {
				return fmt.Errorf("pool mount %q has an invalid branch %q", entry.MountPath, branch)
			}
		}
	default:
		return fmt.Errorf("mount kind %q is invalid", entry.Kind)
	}
	return nil
}

func safeBranchPath(value string) bool {
	segment, ok := strings.CutPrefix(value, "/srv/disks/")
	return ok && validUnitSegment(segment)
}

// MountUnitName converts a canonical mount path into its systemd unit name.
// Branch and pool names are restricted to characters that need no escaping.
func MountUnitName(mountPath string) (string, error) {
	_, segment, found := strings.Cut(mountPath, "/srv/disks/")
	if found {
		if !validUnitSegment(segment) {
			return "", fmt.Errorf("mount path %q cannot be mapped to a unit name", mountPath)
		}
		return "srv-disks-" + segment + ".mount", nil
	}
	segment, found = strings.CutPrefix(mountPath, "/srv/pools/")
	if found {
		if !validUnitSegment(segment) {
			return "", fmt.Errorf("mount path %q cannot be mapped to a unit name", mountPath)
		}
		return "srv-pools-" + segment + ".mount", nil
	}
	return "", fmt.Errorf("mount path %q is outside /srv/disks and /srv/pools", mountPath)
}

func validUnitSegment(value string) bool {
	if value == "" {
		return false
	}
	for _, char := range value {
		switch {
		case char >= 'a' && char <= 'z', char >= 'A' && char <= 'Z', char >= '0' && char <= '9', char == '.', char == '_', char == '-':
		default:
			return false
		}
	}
	return true
}

// RenderMountUnits renders the systemd mount units for a desired mount
// state. Pools declare Requires=/After= on their branch units so ordering
// is enforced by systemd at boot.
func RenderMountUnits(entries []MountEntry) (map[string]string, error) {
	normalized, err := NormalizeMountEntries(entries)
	if err != nil {
		return nil, err
	}
	units := make(map[string]string, len(normalized))
	for _, entry := range normalized {
		name, err := MountUnitName(entry.MountPath)
		if err != nil {
			return nil, err
		}
		var builder strings.Builder
		builder.WriteString("# " + UnitDirectoryHint + "\n")
		builder.WriteString("[Unit]\n")
		switch entry.Kind {
		case "disk":
			fmt.Fprintf(&builder, "Description=LumoNAS disk %s mounted at %s\n", entry.TargetID, entry.MountPath)
		case "pool":
			fmt.Fprintf(&builder, "Description=LumoNAS pool %s mounted at %s\n", entry.TargetID, entry.MountPath)
			dependencies := make([]string, 0, strings.Count(entry.Source, ":")+1)
			for _, branch := range strings.Split(entry.Source, ":") {
				dependency, err := MountUnitName(branch)
				if err != nil {
					return nil, fmt.Errorf("pool %q branch %q: %w", entry.TargetID, branch, err)
				}
				dependencies = append(dependencies, dependency)
			}
			sort.Strings(dependencies)
			fmt.Fprintf(&builder, "Requires=%s\n", strings.Join(dependencies, " "))
			fmt.Fprintf(&builder, "After=%s\n", strings.Join(dependencies, " "))
		}
		builder.WriteString("[Mount]\n")
		fmt.Fprintf(&builder, "What=%s\n", entry.Source)
		fmt.Fprintf(&builder, "Where=%s\n", entry.MountPath)
		fmt.Fprintf(&builder, "Type=%s\n", entry.FSType)
		options := entry.Options
		if options == "" {
			if entry.Kind == "pool" {
				options = PoolMountOptions
			} else {
				options = DiskMountOptions
			}
		}
		fmt.Fprintf(&builder, "Options=%s\n", options)
		builder.WriteString("\n[Install]\nWantedBy=multi-user.target\n")
		units[name] = builder.String()
	}
	return units, nil
}
