package shares

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// WriteValidated writes a generated service configuration to a temporary file,
// validates that file, and activates it only after validation succeeds.
func WriteValidated(path, content string, validate func(string) error) error {
	if validate == nil {
		validate = func(string) error { return nil }
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return err
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), ".lumonas-validated-*")
	if err != nil {
		return err
	}
	temporaryPath := temporary.Name()
	cleanup := func() {
		_ = temporary.Close()
		_ = os.Remove(temporaryPath)
	}
	if _, err := temporary.WriteString(content); err != nil {
		cleanup()
		return err
	}
	if err := temporary.Chmod(0o640); err != nil {
		cleanup()
		return err
	}
	if err := temporary.Close(); err != nil {
		_ = os.Remove(temporaryPath)
		return err
	}
	if err := validate(temporaryPath); err != nil {
		_ = os.Remove(temporaryPath)
		return fmt.Errorf("configuration validation failed: %w", err)
	}
	if err := os.Rename(temporaryPath, path); err != nil {
		_ = os.Remove(temporaryPath)
		return err
	}
	return nil
}

func RenderNFS(values []ManagedShare) (string, error) {
	ordered := append([]ManagedShare(nil), values...)
	sort.Slice(ordered, func(left, right int) bool { return ordered[left].Name < ordered[right].Name })
	var builder strings.Builder
	builder.WriteString("# Generated by LumoNAS. Do not edit.\n")
	for _, share := range ordered {
		if !share.Enabled {
			continue
		}
		protocol, ok := protocolSettings(share, "nfs")
		if !ok {
			continue
		}
		if err := share.Validate(); err != nil {
			return "", err
		}
		networks, err := cidrSettings(protocol, "allowedNetworks")
		if err != nil {
			return "", fmt.Errorf("share %q: %w", share.Name, err)
		}
		if len(networks) == 0 {
			networks = []string{"127.0.0.1/32"}
		}
		rootSquash := true
		if value, exists := protocol["rootSquash"]; exists {
			var valid bool
			rootSquash, valid = value.(bool)
			if !valid {
				return "", fmt.Errorf("share %q: nfs rootSquash must be boolean", share.Name)
			}
		}
		readOnly := false
		if value, exists := protocol["readOnly"]; exists {
			var valid bool
			readOnly, valid = value.(bool)
			if !valid {
				return "", fmt.Errorf("share %q: nfs readOnly must be boolean", share.Name)
			}
		}
		mode := "rw"
		if readOnly {
			mode = "ro"
		}
		for _, network := range networks {
			builder.WriteString(share.Path)
			builder.WriteString(" ")
			builder.WriteString(network)
			builder.WriteString("(")
			builder.WriteString(mode)
			builder.WriteString(",sync,")
			if rootSquash {
				builder.WriteString("root_squash")
			} else {
				builder.WriteString("no_root_squash")
			}
			builder.WriteString(")\n")
		}
	}
	return builder.String(), nil
}

func RenderSFTP(values []ManagedShare) (string, error) {
	ordered := append([]ManagedShare(nil), values...)
	sort.Slice(ordered, func(left, right int) bool { return ordered[left].Name < ordered[right].Name })
	var builder strings.Builder
	builder.WriteString("# Generated by LumoNAS. Include from sshd_config.\nSubsystem sftp internal-sftp\n")
	for _, share := range ordered {
		if !share.Enabled {
			continue
		}
		if _, ok := protocolSettings(share, "sftp"); !ok {
			continue
		}
		if err := share.Validate(); err != nil {
			return "", err
		}
		chroot := share.Path
		readOnly := false
		if settings, ok := protocolSettings(share, "sftp"); ok {
			if value, exists := settings["chroot"]; exists {
				chroot = value.(string)
			}
			if value, exists := settings["readOnly"]; exists {
				readOnly = value.(bool)
			}
		}
		for _, rule := range share.Access {
			if rule.PrincipalName == "" {
				return "", fmt.Errorf("share %q: SFTP access requires resolved principal names", share.Name)
			}
			if rule.Level == "none" {
				continue
			}
			builder.WriteString("Match User ")
			builder.WriteString(rule.PrincipalName)
			builder.WriteString("\n    ChrootDirectory ")
			builder.WriteString(chroot)
			builder.WriteString("\n    ForceCommand internal-sftp")
			if readOnly {
				builder.WriteString(" -R")
			}
			builder.WriteString("\n    X11Forwarding no\n    AllowTcpForwarding no\n")
		}
	}
	return builder.String(), nil
}

func RenderFTP(values []ManagedShare) (string, error) {
	ordered := append([]ManagedShare(nil), values...)
	sort.Slice(ordered, func(left, right int) bool { return ordered[left].Name < ordered[right].Name })
	var builder strings.Builder
	builder.WriteString("# Generated by LumoNAS. Plain FTP is legacy and risky; prefer FTPS.\n")
	for _, share := range ordered {
		if !share.Enabled {
			continue
		}
		if err := share.Validate(); err != nil {
			return "", err
		}
		for _, protocolValue := range share.Protocols {
			if protocolValue.Name != "ftp" && protocolValue.Name != "ftps" {
				continue
			}
			protocol := protocolValue.Settings
			builder.WriteString("share ")
			builder.WriteString(share.Name)
			builder.WriteString(" path=")
			builder.WriteString(share.Path)
			if protocolValue.Name == "ftps" {
				builder.WriteString(" tls=required")
			} else {
				builder.WriteString(" tls=legacy-warning")
			}
			if start, exists := protocol["passivePortStart"]; exists {
				builder.WriteString(" passive_start=")
				builder.WriteString(strconv.Itoa(numberSetting(start)))
			}
			if end, exists := protocol["passivePortEnd"]; exists {
				builder.WriteString(" passive_end=")
				builder.WriteString(strconv.Itoa(numberSetting(end)))
			}
			builder.WriteString("\n")
		}
	}
	return builder.String(), nil
}

func RenderRsync(values []ManagedShare) (string, error) {
	ordered := append([]ManagedShare(nil), values...)
	sort.Slice(ordered, func(left, right int) bool { return ordered[left].Name < ordered[right].Name })
	var builder strings.Builder
	builder.WriteString("# Generated by LumoNAS.\nuid = nobody\ngid = nogroup\nuse chroot = yes\n")
	for _, share := range ordered {
		settings, ok := protocolSettings(share, "rsync")
		if !share.Enabled || !ok {
			continue
		}
		if err := share.Validate(); err != nil {
			return "", err
		}
		builder.WriteString("[")
		builder.WriteString(share.Name)
		builder.WriteString("]\npath = ")
		builder.WriteString(share.Path)
		builder.WriteString("\nread only = ")
		readOnly := false
		if value, exists := settings["readOnly"]; exists {
			var valid bool
			readOnly, valid = value.(bool)
			if !valid {
				return "", fmt.Errorf("share %q: rsync readOnly must be boolean", share.Name)
			}
		}
		builder.WriteString(strconv.FormatBool(readOnly))
		builder.WriteString("\n\n")
	}
	return builder.String(), nil
}

func protocolSettings(share ManagedShare, name string) (map[string]any, bool) {
	for _, protocol := range share.Protocols {
		if protocol.Name == name {
			if protocol.Settings == nil {
				return map[string]any{}, true
			}
			return protocol.Settings, true
		}
	}
	return nil, false
}

func cidrSettings(settings map[string]any, key string) ([]string, error) {
	value, ok := settings[key]
	if !ok {
		return nil, nil
	}
	items, ok := networkStrings(value)
	if !ok {
		return nil, errors.New("allowedNetworks must be an array")
	}
	result := make([]string, 0, len(items))
	for _, item := range items {
		if parseCIDR(item) == nil {
			return nil, fmt.Errorf("network %q is not a valid CIDR", item)
		}
		result = append(result, item)
	}
	return result, nil
}

func numberSetting(value any) int {
	switch value := value.(type) {
	case int:
		return value
	case float64:
		return int(value)
	default:
		return 0
	}
}
