package shares

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// WriteValidated writes a generated service configuration to a temporary file,
// validates that file, and activates it only after validation succeeds.
func WriteValidated(path, content string, validate func(string) error) error {
	if validate == nil {
		validate = func(string) error { return nil }
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return err
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), ".lumonas-validated-*")
	if err != nil {
		return err
	}
	temporaryPath := temporary.Name()
	cleanup := func() {
		_ = temporary.Close()
		_ = os.Remove(temporaryPath)
	}
	if _, err := temporary.WriteString(content); err != nil {
		cleanup()
		return err
	}
	if err := temporary.Chmod(0o640); err != nil {
		cleanup()
		return err
	}
	if err := temporary.Close(); err != nil {
		_ = os.Remove(temporaryPath)
		return err
	}
	if err := validate(temporaryPath); err != nil {
		_ = os.Remove(temporaryPath)
		return fmt.Errorf("configuration validation failed: %w", err)
	}
	if err := os.Rename(temporaryPath, path); err != nil {
		_ = os.Remove(temporaryPath)
		return err
	}
	return nil
}

func RenderNFS(values []ManagedShare) (string, error) {
	ordered := append([]ManagedShare(nil), values...)
	sort.Slice(ordered, func(left, right int) bool { return ordered[left].Name < ordered[right].Name })
	var builder strings.Builder
	builder.WriteString("# Generated by LumoNAS. Do not edit.\n")
	for _, share := range ordered {
		if !share.Enabled {
			continue
		}
		protocol, ok := protocolSettings(share, "nfs")
		if !ok {
			continue
		}
		if err := share.Validate(); err != nil {
			return "", err
		}
		networks, err := cidrSettings(protocol, "allowedNetworks")
		if err != nil {
			return "", fmt.Errorf("share %q: %w", share.Name, err)
		}
		if len(networks) == 0 {
			networks = []string{"127.0.0.1/32"}
		}
		rootSquash := true
		if value, exists := protocol["rootSquash"]; exists {
			var valid bool
			rootSquash, valid = value.(bool)
			if !valid {
				return "", fmt.Errorf("share %q: nfs rootSquash must be boolean", share.Name)
			}
		}
		readOnly := false
		if value, exists := protocol["readOnly"]; exists {
			var valid bool
			readOnly, valid = value.(bool)
			if !valid {
				return "", fmt.Errorf("share %q: nfs readOnly must be boolean", share.Name)
			}
		}
		mode := "rw"
		if readOnly {
			mode = "ro"
		}
		for _, network := range networks {
			builder.WriteString(share.Path)
			builder.WriteString(" ")
			builder.WriteString(network)
			builder.WriteString("(")
			builder.WriteString(mode)
			builder.WriteString(",sync,")
			if rootSquash {
				builder.WriteString("root_squash")
			} else {
				builder.WriteString("no_root_squash")
			}
			builder.WriteString(")\n")
		}
	}
	return builder.String(), nil
}

func RenderSFTP(values []ManagedShare) (string, error) {
	ordered := append([]ManagedShare(nil), values...)
	sort.Slice(ordered, func(left, right int) bool { return ordered[left].Name < ordered[right].Name })
	var builder strings.Builder
	builder.WriteString("# Generated by LumoNAS. Include from sshd_config.\nSubsystem sftp internal-sftp\n")
	for _, share := range ordered {
		if !share.Enabled {
			continue
		}
		if _, ok := protocolSettings(share, "sftp"); !ok {
			continue
		}
		if err := share.Validate(); err != nil {
			return "", err
		}
		chroot := share.Path
		readOnly := false
		if settings, ok := protocolSettings(share, "sftp"); ok {
			if value, exists := settings["chroot"]; exists {
				chroot = value.(string)
			}
			if value, exists := settings["readOnly"]; exists {
				readOnly = value.(bool)
			}
		}
		for _, rule := range share.Access {
			if rule.PrincipalName == "" {
				return "", fmt.Errorf("share %q: SFTP access requires resolved principal names", share.Name)
			}
			if rule.Level == "none" {
				continue
			}
			builder.WriteString("Match User ")
			builder.WriteString(rule.PrincipalName)
			builder.WriteString("\n    ChrootDirectory ")
			builder.WriteString(chroot)
			builder.WriteString("\n    ForceCommand internal-sftp")
			if readOnly {
				builder.WriteString(" -R")
			}
			builder.WriteString("\n    X11Forwarding no\n    AllowTcpForwarding no\n")
		}
	}
	return builder.String(), nil
}

// FTPOptions carries deployment-specific paths needed to render a complete
// vsftpd configuration.
type FTPOptions struct {
	UserConfigDir string
	TLSCertFile   string
	TLSKeyFile    string
}

// FTPConfig is the vsftpd rendering result: one global config plus one
// config file per FTP user (vsftpd user_config_dir convention).
type FTPConfig struct {
	Main  string
	Users map[string]string
}

// RenderFTPConfig renders a valid vsftpd configuration from the managed
// shares: global directives in Main, and per-user files in Users mapping
// each principal to its share root via local_root. A principal referenced
// by multiple FTP shares with different roots is rejected, because vsftpd
// supports exactly one local_root per user.
func RenderFTPConfig(values []ManagedShare, options FTPOptions) (FTPConfig, error) {
	ordered := append([]ManagedShare(nil), values...)
	sort.Slice(ordered, func(left, right int) bool { return ordered[left].Name < ordered[right].Name })
	if options.UserConfigDir == "" {
		return FTPConfig{}, errors.New("FTP user config directory is required")
	}
	config := FTPConfig{Users: make(map[string]string)}
	tlsEnabled := false
	passiveStart, passiveEnd := 0, 0
	for _, share := range ordered {
		if !share.Enabled {
			continue
		}
		if err := share.Validate(); err != nil {
			return FTPConfig{}, err
		}
		for _, protocol := range share.Protocols {
			if protocol.Name != "ftp" && protocol.Name != "ftps" {
				continue
			}
			if protocol.Name == "ftps" {
				tlsEnabled = true
			}
			if start := numberSetting(protocol.Settings["passivePortStart"]); start > passiveStart {
				passiveStart = start
			}
			if end := numberSetting(protocol.Settings["passivePortEnd"]); end > passiveEnd {
				passiveEnd = end
			}
			for _, rule := range share.Access {
				if rule.Level == "none" || rule.PrincipalName == "" {
					continue
				}
				existing, mapped := config.Users[rule.PrincipalName]
				root := "local_root=" + share.Path + "\n"
				if mapped && existing != root {
					return FTPConfig{}, fmt.Errorf("principal %q maps to multiple FTP roots", rule.PrincipalName)
				}
				writeEnable := "write_enable=YES\n"
				if rule.Level != "write" || boolSetting(protocol.Settings["readOnly"]) {
					writeEnable = "write_enable=NO\n"
				}
				config.Users[rule.PrincipalName] = "# Generated by LumoNAS. Do not edit.\n" + root + writeEnable
			}
		}
	}
	if passiveStart <= 0 {
		passiveStart = 50000
	}
	if passiveEnd <= passiveStart {
		passiveEnd = passiveStart + 1000
	}
	var builder strings.Builder
	builder.WriteString("# Generated by LumoNAS. Do not edit.\n")
	builder.WriteString("# Plain FTP is legacy and risky; prefer FTPS.\n")
	builder.WriteString("listen=YES\n")
	builder.WriteString("anonymous_enable=NO\n")
	builder.WriteString("local_enable=YES\n")
	builder.WriteString("chroot_local_user=YES\n")
	builder.WriteString("allow_writeable_chroot=NO\n")
	builder.WriteString("xferlog_enable=YES\n")
	builder.WriteString("connect_from_port_20=YES\n")
	builder.WriteString("pam_service_name=vsftpd\n")
	builder.WriteString("secure_chroot_dir=/var/run/vsftpd/empty\n")
	builder.WriteString("user_config_dir=" + options.UserConfigDir + "\n")
	fmt.Fprintf(&builder, "pasv_enable=YES\npasv_min_port=%d\npasv_max_port=%d\n", passiveStart, passiveEnd)
	if tlsEnabled {
		cert, key := options.TLSCertFile, options.TLSKeyFile
		if cert == "" || key == "" {
			return FTPConfig{}, errors.New("FTPS requires TLS certificate and key paths")
		}
		builder.WriteString("ssl_enable=YES\n")
		builder.WriteString("force_local_logins_ssl=YES\n")
		builder.WriteString("force_local_data_ssl=YES\n")
		builder.WriteString("ssl_tlsv1_2=YES\n")
		builder.WriteString("rsa_cert_file=" + cert + "\n")
		builder.WriteString("rsa_private_key_file=" + key + "\n")
	}
	config.Main = builder.String()
	return config, nil
}

func RenderRsync(values []ManagedShare) (string, error) {
	ordered := append([]ManagedShare(nil), values...)
	sort.Slice(ordered, func(left, right int) bool { return ordered[left].Name < ordered[right].Name })
	var builder strings.Builder
	builder.WriteString("# Generated by LumoNAS.\nuid = nobody\ngid = nogroup\nuse chroot = yes\n")
	for _, share := range ordered {
		settings, ok := protocolSettings(share, "rsync")
		if !share.Enabled || !ok {
			continue
		}
		if err := share.Validate(); err != nil {
			return "", err
		}
		builder.WriteString("[")
		builder.WriteString(share.Name)
		builder.WriteString("]\npath = ")
		builder.WriteString(share.Path)
		builder.WriteString("\nread only = ")
		readOnly := false
		if value, exists := settings["readOnly"]; exists {
			var valid bool
			readOnly, valid = value.(bool)
			if !valid {
				return "", fmt.Errorf("share %q: rsync readOnly must be boolean", share.Name)
			}
		}
		builder.WriteString(strconv.FormatBool(readOnly))
		builder.WriteString("\n\n")
	}
	return builder.String(), nil
}

func protocolSettings(share ManagedShare, name string) (map[string]any, bool) {
	for _, protocol := range share.Protocols {
		if protocol.Name == name {
			if protocol.Settings == nil {
				return map[string]any{}, true
			}
			return protocol.Settings, true
		}
	}
	return nil, false
}

func cidrSettings(settings map[string]any, key string) ([]string, error) {
	value, ok := settings[key]
	if !ok {
		return nil, nil
	}
	items, ok := networkStrings(value)
	if !ok {
		return nil, errors.New("allowedNetworks must be an array")
	}
	result := make([]string, 0, len(items))
	for _, item := range items {
		if parseCIDR(item) == nil {
			return nil, fmt.Errorf("network %q is not a valid CIDR", item)
		}
		result = append(result, item)
	}
	return result, nil
}

func numberSetting(value any) int {
	switch value := value.(type) {
	case int:
		return value
	case float64:
		return int(value)
	default:
		return 0
	}
}

func boolSetting(value any) bool {
	result, _ := value.(bool)
	return result
}
