package shares

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type Share struct {
	ID          string            `json:"id"`
	Name        string            `json:"name"`
	Path        string            `json:"path"`
	Description string            `json:"description,omitempty"`
	Enabled     bool              `json:"enabled"`
	Protocols   []string          `json:"protocols"`
	Access      map[string]string `json:"access"`
	Guest       bool              `json:"guest"`
}

type Store struct{ Path string }

func (s Store) Load() ([]Share, error) {
	data, err := os.ReadFile(s.Path)
	if errors.Is(err, os.ErrNotExist) {
		return []Share{}, nil
	}
	if err != nil {
		return nil, err
	}
	var result []Share
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, fmt.Errorf("parse shares: %w", err)
	}
	return result, nil
}

func (s Store) Save(values []Share) error {
	if err := os.MkdirAll(filepath.Dir(s.Path), 0o750); err != nil {
		return err
	}
	data, err := json.MarshalIndent(values, "", "  ")
	if err != nil {
		return err
	}
	temporary, err := os.CreateTemp(filepath.Dir(s.Path), ".shares-*.json")
	if err != nil {
		return err
	}
	tempPath := temporary.Name()
	defer os.Remove(tempPath)
	if _, err := temporary.Write(append(data, '\n')); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Chmod(0o640); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	return os.Rename(tempPath, s.Path)
}

func Validate(share Share) error {
	if !regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9 _.-]{0,63}$`).MatchString(share.Name) {
		return errors.New("share name contains unsupported characters")
	}
	if !filepath.IsAbs(share.Path) || strings.ContainsRune(share.Path, '\x00') {
		return errors.New("share path must be an absolute local path")
	}
	if len(share.Protocols) == 0 {
		return errors.New("at least one share protocol is required")
	}
	for _, protocol := range share.Protocols {
		switch protocol {
		case "smb", "nfs", "sftp", "ftp", "rsync":
		default:
			return fmt.Errorf("unsupported share protocol %q", protocol)
		}
	}
	for principal, level := range share.Access {
		if strings.TrimSpace(principal) == "" {
			return errors.New("access principal cannot be empty")
		}
		switch level {
		case "none", "read", "write":
		default:
			return fmt.Errorf("unsupported access level %q", level)
		}
	}
	return nil
}

func RenderSamba(values []Share) (string, error) {
	ordered := append([]Share(nil), values...)
	sort.Slice(ordered, func(left, right int) bool { return ordered[left].Name < ordered[right].Name })
	var builder strings.Builder
	builder.WriteString("# Generated by LumoNAS. Do not edit; use the management API.\n[global]\n   server min protocol = SMB2\n   map to guest = Never\n\n")
	for _, share := range ordered {
		if !share.Enabled {
			continue
		}
		if err := Validate(share); err != nil {
			return "", err
		}
		builder.WriteString("[")
		builder.WriteString(share.Name)
		builder.WriteString("]\n   path = ")
		builder.WriteString(share.Path)
		builder.WriteString("\n   browseable = yes\n   read only = no\n   guest ok = ")
		if share.Guest {
			builder.WriteString("yes\n\n")
		} else {
			builder.WriteString("no\n\n")
		}
	}
	return builder.String(), nil
}

func WriteGenerated(path, config string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return err
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), ".smb-*.conf")
	if err != nil {
		return err
	}
	tempPath := temporary.Name()
	defer os.Remove(tempPath)
	if _, err := temporary.WriteString(config); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Chmod(0o640); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	return os.Rename(tempPath, path)
}

func ValidateSamba(configPath string) error {
	if _, err := exec.LookPath("testparm"); err != nil {
		return nil
	}
	command := exec.Command("testparm", "-s", configPath)
	if output, err := command.CombinedOutput(); err != nil {
		return fmt.Errorf("testparm: %s", strings.TrimSpace(string(output)))
	}
	return nil
}
