import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('lumonas-onboarded', '1'))
})

test('Files creates a folder, completes a resumable upload, searches, and restores a deleted item', async ({ page }) => {
  await page.goto('/files?share=share-documents')
  await page.getByRole('button', { name: 'New folder' }).click()
  await page.getByPlaceholder('Folder name').fill('E2E Folder')
  await page.getByRole('dialog').getByRole('button', { name: 'Create' }).click()
  await expect(page.getByText('E2E Folder', { exact: true })).toBeVisible()

  await page.locator('input[type="file"]').setInputFiles({ name: 'e2e-upload.txt', mimeType: 'text/plain', buffer: Buffer.from('upload from Playwright') })
  await expect(page.getByRole('region', { name: 'Recent upload submissions' }).getByText('e2e-upload.txt')).toBeVisible()
  await expect(page.getByText('e2e-upload.txt').last()).toBeVisible()

  await page.getByRole('button', { name: 'Search', exact: true }).click()
  await page.getByPlaceholder('vacation-2024.jpg').fill('invoice')
  await expect(page.getByText('invoice-0042.pdf')).toBeVisible()

  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: /Recycle bin/ }).click()
  await expect(page.getByText('draft-contract.docx')).toBeVisible()
  await page.getByRole('button', { name: 'Restore draft-contract.docx' }).click()
  await expect(page.getByText('draft-contract.docx')).toHaveCount(0)
})

test('Files previews supported media without offering inline rendering for other files', async ({ page }) => {
  await page.route('**/api/v1/files/download?*', async (route) => {
    const request = new URL(route.request().url())
    if (request.searchParams.get('inline') !== '1') return route.continue()
    const name = request.searchParams.get('name') ?? ''
    if (name.endsWith('.jpg')) return route.fulfill({ status: 200, contentType: 'image/jpeg', body: Buffer.from([0xff, 0xd8, 0xff, 0xd9]) })
    return route.fulfill({ status: 200, contentType: 'text/plain; charset=utf-8', body: 'safe preview fixture' })
  })
  await page.goto('/files?share=share-photos&path=%2F2025')
  await page.getByRole('button', { name: 'Actions for IMG_5501.jpg' }).click()
  await page.getByRole('menuitem', { name: 'Preview' }).click()
  await expect(page.getByRole('dialog')).toContainText('IMG_5501.jpg')
  await expect(page.getByRole('img', { name: 'IMG_5501.jpg' })).toBeVisible()
  await page.keyboard.press('Escape')

  await page.goto('/files?share=share-documents')
  await page.getByRole('button', { name: 'Actions for house-insurance.pdf' }).click()
  await expect(page.getByRole('menuitem', { name: 'Preview' })).toHaveCount(0)
  await expect(page.getByRole('menuitem', { name: 'Download' })).toBeVisible()

  await page.goto('/files?share=share-media')
  await page.getByRole('button', { name: 'Actions for readme.txt' }).click()
  await page.getByRole('menuitem', { name: 'Preview' }).click()
  await expect(page.getByTitle('Preview of readme.txt')).toBeVisible()
})

test('Files browses snapshot history and queues a no-overwrite restore', async ({ page }) => {
  await page.goto('/files?share=share-documents')
  await page.getByRole('button', { name: 'File history' }).click()
  const history = page.getByRole('dialog').first()
  await expect(history.getByRole('heading', { name: 'File history' })).toBeVisible()
  await history.getByRole('button', { name: /BTRFS ·/ }).first().click()
  await history.getByRole('button', { name: 'Compare with current' }).click()
  await expect(history.getByText(/1 added · 2 modified · 4 deleted/)).toBeVisible()
  await expect(history.getByText('Documents/old-contract.pdf')).toBeVisible()
  await history.getByRole('button', { name: 'Restore copy' }).last().click()
  const recovery = page.getByRole('dialog').last()
  await expect(recovery.getByRole('heading', { name: 'Restore old-contract.pdf?' })).toBeVisible()
  await expect(recovery.getByLabel('Restore into share folder')).toHaveValue(/Recovered from/)
  await recovery.getByRole('button', { name: 'Restore copy' }).click()
  await expect(page.getByText('Snapshot restore queued').first()).toBeVisible()
  await history.getByRole('button', { name: 'Documents' }).click()
  await expect(history.getByText('family-photo.jpg')).toBeVisible()
  await history.getByRole('button', { name: 'Restore…' }).click()
  await page.getByRole('dialog').last().getByRole('button', { name: 'Restore copy' }).click()
  await expect(page.getByText('Snapshot restore queued').first()).toBeVisible()
})

test('Files establishes and verifies a share integrity baseline', async ({ page }) => {
  await page.goto('/files?share=share-documents')
  await page.getByRole('button', { name: 'Integrity' }).click()
  await expect(page.getByRole('heading', { name: 'File integrity' })).toBeVisible()
  await page.getByRole('button', { name: 'Create baseline' }).click()
  await expect(page.getByText(/Baseline:/)).toBeVisible()
  await page.getByRole('button', { name: 'Verify now' }).click()
  await expect(page.getByText('1 changed')).toBeVisible()
  await expect(page.getByText('1 added')).toBeVisible()
  await expect(page.getByText('notes.txt')).toBeVisible()
})

test('Storage plans encrypted formatting and only confirms after passphrase and safety unlock', async ({ page }) => {
  await page.goto('/storage?disk=disk-external')
  await page.getByRole('button', { name: 'Format & mount disk' }).click()
  await page.getByLabel('Type sdh to confirm').fill('sdh')
  await page.getByRole('dialog').getByRole('button', { name: 'Format & mount disk' }).click()
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Plan operation' }).click()
  await expect(page.getByText('LUKS passphrase')).toBeVisible()
  await page.getByLabel('LUKS passphrase').fill('correct horse battery staple')
  await expect(page.getByRole('button', { name: 'Confirm format & mount' })).toBeDisabled()
  await page.getByLabel('Confirm passphrase').fill('correct horse battery staple')
  await expect(page.getByRole('button', { name: 'Confirm format & mount' })).toBeEnabled()
  await page.getByRole('button', { name: 'Unlock (15 min)' }).click()
  await page.getByRole('button', { name: 'Confirm format & mount' }).click()
  await expect(page.getByText('Storage operation completed')).toBeVisible()
})

test('Shares previews effective access and edits share settings', async ({ page }) => {
  await page.goto('/shares')
  await page.getByRole('button', { name: /Preview/ }).first().click()
  await expect(page.getByRole('heading', { name: 'Effective share access' })).toBeVisible()
  await expect(page.getByText('Administrators').first()).toBeVisible()
  await page.keyboard.press('Escape')

  await page.getByRole('row').filter({ hasText: 'Media' }).click()
  await expect(page.getByRole('tab', { name: 'Access' })).toHaveAttribute('aria-selected', 'true')
  await page.getByRole('tab', { name: 'Protocols' }).click()
  await expect(page.getByRole('switch', { name: 'Toggle nfs' })).toBeVisible()
  await page.getByRole('tab', { name: 'Settings' }).click()
  await expect(page.getByLabel('Description')).toBeVisible()
})

test('Shares gives actionable Windows and macOS backup setup instructions', async ({ page }) => {
  await page.goto('/shares')
  await expect(page.getByText('Set up a computer backup', { exact: true })).toBeVisible()
  await expect(page.getByText('NAS readiness only:', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'macOS' }).click()
  await expect(page.getByText(/System Settings → General → Time Machine/)).toBeVisible()
  await page.getByRole('button', { name: 'Windows' }).click()
  await expect(page.getByText(/Control Panel → File History/)).toBeVisible()
})

test('Backups runs a job, verifies recovery, stages restore, and pairs a replication peer', async ({ page }) => {
  await page.goto('/backups?tab=jobs')
  await page.getByRole('button', { name: 'Run now' }).first().click()
  await expect(page.getByText(/Backup queued/)).toBeVisible()

  await page.goto('/backups?tab=recovery')
  await expect(page.getByText(/Latest bundle:/)).toBeVisible()
  await page.getByRole('button', { name: 'Run drill now' }).click()
  await expect(page.getByText('successful')).toBeVisible()
  await page.getByRole('button', { name: 'Stage restore' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Stage bundle' }).click()

  await page.goto('/backups?tab=replication')
  await page.getByRole('button', { name: 'Pair NAS' }).click()
  await page.getByRole('dialog').getByLabel('Name').fill('E2E remote NAS')
  await page.getByLabel('Destination URL').fill('https://nas.example.test')
  await page.getByLabel('Receive-only replication token').fill('e2e-receive-token')
  await page.getByLabel('Fleet status token (recommended)').fill('e2e-fleet-token')
  await page.getByRole('dialog').getByRole('button', { name: 'Pair NAS' }).click()
  await expect(page.getByText('E2E remote NAS').last()).toBeVisible()
  await page.getByRole('button', { name: 'Replicate now' }).last().click()
  await expect(page.getByText('current').first()).toBeVisible()
})

test('Backups restores a verified VM generation and leaves the guest stopped', async ({ page }) => {
  await page.goto('/backups?tab=recovery')
  await page.getByLabel('Backup destination').selectOption('dest-usb')
  await page.getByLabel('VM backup generation').selectOption('run-e2e-vm')
  await page.getByLabel('VM to restore').selectOption('media-vm')
  await page.getByRole('button', { name: 'Restore…' }).click()
  await page.getByLabel('Confirm VM name').fill('media-vm')
  await page.getByRole('button', { name: 'Restore stopped VM' }).click()
  await expect(page.getByText('VM restored stopped; review its settings before starting it')).toBeVisible()
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('Recovery shows app-data coverage and stages only the selected stack', async ({ page }) => {
  await page.goto('/backups?tab=recovery')
  await expect(page.getByText('App data coverage', { exact: true })).toBeVisible()
  await expect(page.getByText('1 of 1 configured path in latest bundle')).toBeVisible()
  page.on('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Stage app data' }).first().click()
  await expect(page.getByText('jellyfin app data staged for offline recovery')).toBeVisible()
})

test('Recovery downloads a replacement migration bundle and its checklist', async ({ page }) => {
  await page.goto('/backups')
  await page.getByRole('button', { name: /Disaster recovery/ }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('checkbox', { name: /fresh system disk/ }).check()
  await page.getByRole('button', { name: 'Approve restore plan' }).click()
  const recoveryDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download recovery bundle' }).click()
  expect((await recoveryDownload).suggestedFilename()).toMatch(/lumonas-recovery\.mrb/)
  const checklistDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download migration checklist' }).click()
  expect((await checklistDownload).suggestedFilename()).toMatch(/lumonas-migration-generation-.*\.json/)
})

test('Backups can run a verified copy when a USB destination connects', async ({ page }) => {
  await page.goto('/backups')
  const usbTrigger = page.getByRole('switch', { name: 'Back up when USB storage connects' })
  await expect(usbTrigger).toBeEnabled()
  await usbTrigger.click()
  await expect(usbTrigger).toBeChecked()
})

test('Network checkpoint rollback and diagnostics complete against the isolated mock', async ({ page }) => {
  await page.goto('/network?tab=diagnostics')
  await page.getByRole('button', { name: 'Open checkpoint' }).click()
  await page.getByRole('button', { name: 'Roll back' }).click()
  await expect(page.getByText('No open checkpoint in this session.')).toBeVisible()

  await page.goto('/network?tab=diagnostics')
  await page.getByRole('button', { name: 'Run diagnostic' }).click()
  await expect(page.getByText('Completed.')).toBeVisible()
})

test('Storage safety gates protected disk replacement until a plan is reviewed', async ({ page }) => {
  await page.goto('/storage?tab=mounts')
  await page.getByRole('button', { name: 'Unlock (15 min)' }).click()
  await expect(page.getByText('Storage safety unlocked', { exact: true })).toBeVisible()

  await page.getByRole('tab', { name: 'Disks' }).click()
  await page.getByRole('row').filter({ hasText: 'sdb' }).click()
  await page.getByRole('button', { name: 'Replace with parity recovery' }).click()
  await page.getByLabel('Replacement disk').click()
  await page.getByRole('option', { name: /E2E-SPARE-001/ }).click()
  await page.getByRole('button', { name: 'Review plan' }).click()
  await expect(page.getByText('Reviewed replacement plan')).toBeVisible()
  const replacementAcknowledgement = page.getByLabel('I verified the failed and replacement disk serial numbers.')
  await replacementAcknowledgement.check()
  await expect(replacementAcknowledgement).toBeChecked()
  await expect(page.getByText('Storage safety is locked')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Start recovery' })).toBeEnabled()
  await page.getByRole('button', { name: 'Start recovery' }).click()
  await expect(page.getByText('Recovery queued')).toBeVisible()
})

test('Users creates a file identity and a group', async ({ page }) => {
  await page.goto('/users')
  await page.getByRole('button', { name: 'Create user' }).click()
  await page.getByLabel('Username').fill('e2e-file-user')
  await page.getByLabel('Password', { exact: true }).fill('long-e2e-password')
  const createResponse = page.waitForResponse((response) => response.url().endsWith('/api/v1/users') && response.request().method() === 'POST')
  await page.getByRole('dialog').getByRole('button', { name: 'Create user' }).click()
  expect((await createResponse).status()).toBe(204)
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect.poll(() => page.evaluate(async () => {
    const response = await fetch('/api/v1/users')
    const users = await response.json() as { file: { username: string }[] }
    return users.file.some((user) => user.username === 'e2e-file-user')
  })).toBe(true)
  await expect(page.getByText('e2e-file-user', { exact: true })).toBeVisible()

  const createGroup = page.getByRole('button', { name: 'Create', exact: true })
  await expect(createGroup).toBeDisabled()
  await page.getByLabel('New group name').fill('e2e-group')
  await expect(createGroup).toBeEnabled()
  await createGroup.click()
  await expect(page.getByText('e2e-group', { exact: true })).toBeVisible()
})

test('Relationships impact-map nodes navigate to the affected resource', async ({ page }) => {
  await page.goto('/dependencies')
  await expect(page.getByText('Impact map')).toBeVisible()
  const disk = page.getByRole('link', { name: /disk/ }).first()
  const target = await disk.getAttribute('href')
  expect(target).toMatch(/^\/storage\?tab=disks&disk=/)
  await disk.click()
  await page.waitForURL((url) => `${url.pathname}${url.search}` === target)
  const diskDrawer = page.getByRole('dialog')
  await expect(diskDrawer).toBeVisible()
  await expect(diskDrawer).toContainText('serial')
})

test('Settings creates a scoped API token and revokes it with confirmation', async ({ page }) => {
  await page.goto('/settings?tab=security')
  await expect(page.getByText('TLS certificate')).toBeVisible()
  await expect(page.getByText('valid', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Create token' }).click()
  await page.getByLabel('Name', { exact: true }).fill('E2E monitoring token')
  await page.getByRole('dialog').getByRole('button', { name: 'Create token' }).click()
  await expect(page.getByText('lumo_e2e_mock_token_once')).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: 'Done' }).click()

  page.on('dialog', (dialog) => dialog.accept())
  await page.locator('li').filter({ hasText: 'E2E monitoring token' }).getByRole('button', { name: 'Revoke' }).click()
  await expect(page.getByText('E2E monitoring token')).toHaveCount(0)
})

test('Settings creates a workstation backup token bound to one selected share', async ({ page }) => {
  await page.goto('/settings?tab=security')
  await page.getByRole('button', { name: 'Create token' }).click()
  await page.getByLabel('Name', { exact: true }).fill('E2E laptop backup')
  await page.getByLabel('Back up and restore one workstation on a single share').check()
  await page.getByLabel('Dedicated backup share').selectOption('share-backups')
  await page.getByRole('dialog').getByRole('button', { name: 'Create token' }).click()
  await expect(page.getByText('lumo_e2e_mock_token_once')).toBeVisible()
  await expect(page.getByRole('dialog').last().getByText('workstation:backup:share-backups', { exact: true })).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: 'Done' }).click()
  await expect(page.locator('li').filter({ hasText: 'E2E laptop backup' })).toContainText('workstation:backup:share-backups')
})

test('Monitoring filters and pages the audit log, exports CSV, and checks troubleshooting', async ({ page }) => {
  await page.goto('/monitoring?tab=audit')
  await expect(page.getByRole('row')).toHaveCount(101)
  await page.getByRole('button', { name: 'Next' }).click()
  await expect(page.getByRole('row')).toHaveCount(6)
  await page.getByRole('button', { name: 'Previous' }).click()
  await page.getByLabel('Filter by actor').fill('admin')
  await expect(page.getByText('system', { exact: true })).toHaveCount(0)
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export CSV' }).click()
  expect((await download).suggestedFilename()).toMatch(/lumonas-audit-.*\.csv/)

  await page.goto('/monitoring?tab=troubleshooting')
  await expect(page.getByText('No active issues')).toBeVisible()
})

test('Monitoring routes critical alerts to selected notification channels', async ({ page }) => {
  await page.goto('/monitoring?tab=notifications')
  await page.getByRole('button', { name: 'Add rule' }).click()
  await page.getByLabel('Name').fill('Critical storage page')
  await page.getByLabel('Condition').fill('category = storage')
  await page.getByLabel('Minimum severity').selectOption('critical')
  await page.getByRole('checkbox', { name: 'ntfy ntfy' }).check()
  await page.getByRole('button', { name: 'Save rule' }).click()
  await expect(page.getByText('Critical storage page', { exact: true })).toBeVisible()
  await expect(page.getByText('critical', { exact: true }).last()).toBeVisible()
})

test('Monitoring can cancel a queued SMART job from job history', async ({ page }) => {
  await page.goto('/monitoring?tab=jobs')
  const row = page.getByRole('row').filter({ hasText: 'E2E SMART short test — sdc' })
  await expect(row.getByRole('button', { name: 'Cancel' })).toBeVisible()
  await row.getByRole('button', { name: 'Cancel' }).click()
  await expect(row.getByText('cancelled')).toBeVisible()
})

test('Monitoring adds a separate retained snapshot policy for a share', async ({ page }) => {
  await page.goto('/monitoring?tab=jobs')
  await page.getByLabel('New snapshot schedule name').fill('Documents history')
  await page.getByLabel('New snapshot source').fill('/srv/pools/documents')
  await page.getByLabel('New snapshot retention').fill('30')
  await page.getByLabel('New snapshot lock days').fill('90')
  await page.getByRole('button', { name: 'Add snapshot policy' }).click()
  await expect(page.getByText('Snapshot schedule created — Documents history', { exact: true })).toBeVisible()
  await expect(page.getByRole('listitem').filter({ hasText: 'Documents history' }).getByLabel('Snapshot lock days')).toHaveValue('90')
})

test('Docker container actions update the reported state', async ({ page }) => {
  await page.goto('/docker?tab=containers')
  const row = page.getByRole('row').filter({ hasText: 'jellyfin' }).first()
  await row.getByRole('button', { name: 'Stop jellyfin' }).click()
  await expect(row.getByText('Exited')).toBeVisible()
  await row.getByRole('button', { name: 'Start jellyfin' }).click()
  await expect(row.getByText('Running')).toBeVisible()
})

test('Virtual machines report host readiness and support graceful controls', async ({ page }) => {
  await page.goto('/docker?tab=vms')
  await expect(page.getByText('KVM acceleration available')).toBeVisible()
  // The component already stamps each machine row with data-testid, so select
  // that. A broad 'div' filter plus .last() resolves to whichever matching
  // ancestor rendered last, which made this click timing-dependent.
  const machine = page.getByTestId('vm-home-lab')
  await machine.getByRole('button', { name: 'Shut down' }).click()
  await expect(page.getByText('stopped', { exact: true })).toBeVisible()

  await page.getByLabel('Upload installation ISO').setInputFiles({ name: 'e2e-os.iso', mimeType: 'application/x-iso9660-image', buffer: Buffer.from('fixture ISO') })
  await expect(page.getByText('e2e-os.iso', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Create VM' }).click()
  await page.getByLabel('VM name').fill('e2e-new-guest')
  await page.getByLabel('Installer ISO').selectOption('e2e-os.iso')
  await page.getByRole('dialog').getByRole('button', { name: 'Create and boot VM' }).click()
  await expect(page.getByText('e2e-new-guest', { exact: true })).toBeVisible()
  await expect(page.getByText('running', { exact: true }).last()).toBeVisible()

  await page.getByRole('button', { name: 'Serial console' }).click()
  await expect(page.getByRole('log', { name: 'e2e-new-guest serial console output' })).toContainText('Guest serial console ready')
  await page.getByRole('textbox', { name: 'e2e-new-guest serial console input' }).click()
  await page.keyboard.type('help')
  await page.keyboard.press('Enter')
  await page.getByRole('button', { name: 'Close console' }).click()
  await expect(page.getByRole('log', { name: 'e2e-new-guest serial console output' })).toHaveCount(0)

  await page.getByRole('button', { name: 'Snapshots for e2e-new-guest' }).click()
  await page.getByRole('button', { name: 'Create snapshot' }).click()
  const snapshotName = page.getByText(/^before-/).last()
  await expect(snapshotName).toBeVisible()
  await page.getByRole('button', { name: 'Restore snapshot' }).first().click()
  await expect(page.getByRole('dialog').getByText(/replaces the guest’s current state/)).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: 'Restore snapshot' }).click()
  await expect(page.getByText('Virtual machine snapshot restore requested')).toBeVisible()

  await page.getByRole('button', { name: 'Delete snapshot' }).first().click()
  await expect(page.getByRole('dialog').getByText(/permanently removes that recovery point/)).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: 'Delete snapshot' }).click()
  await expect(snapshotName).toHaveCount(0)

  await page.getByRole('button', { name: 'Delete VM' }).last().click()
  let deleteDialog = page.getByRole('dialog')
  await deleteDialog.getByLabel('Type e2e-new-guest to confirm').fill('e2e-new-guest')
  await expect(deleteDialog.getByRole('button', { name: 'Delete VM, keep recovery files' })).toBeDisabled()
  await expect(deleteDialog.getByText(/Shut it down and wait for it to stop/)).toBeVisible()
  await deleteDialog.getByRole('button', { name: 'Cancel' }).click()

  await page.getByRole('button', { name: 'Shut down' }).last().click()
  await expect(page.getByText('stopped', { exact: true }).last()).toBeVisible()
  await page.getByRole('button', { name: 'Delete VM' }).last().click()
  deleteDialog = page.getByRole('dialog')
  await deleteDialog.getByLabel('Type e2e-new-guest to confirm').fill('e2e-new-guest')
  await deleteDialog.getByRole('button', { name: 'Delete VM, keep recovery files' }).click()
  await expect(page.getByTestId('vm-e2e-new-guest')).toHaveCount(0)
  await expect(page.getByText('Saved VM recovery files', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Restore VM definition' }).click()
  await expect(page.getByTestId('vm-e2e-new-guest')).toBeVisible()
  await expect(page.getByText('stopped', { exact: true }).last()).toBeVisible()

  await page.getByRole('button', { name: 'Delete VM' }).last().click()
  deleteDialog = page.getByRole('dialog')
  await deleteDialog.getByLabel('Type e2e-new-guest to confirm').fill('e2e-new-guest')
  await deleteDialog.getByLabel('Permanently delete this disk and all guest data').check()
  await deleteDialog.getByRole('button', { name: 'Delete VM and disk' }).click()
  await expect(page.getByTestId('vm-e2e-new-guest')).toHaveCount(0)
})
