#!/bin/sh
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
SYSTEMD="$ROOT/packaging/systemd"

require_line() {
	file=$1
	pattern=$2
	if ! grep -F -- "$pattern" "$file" >/dev/null 2>&1; then
		echo "missing '$pattern' in $file" >&2
		exit 1
	fi
}

for unit in lumonas-web.service lumonasd.service lumonas-privd.service lumonas-privd-storage.service lumonas-privd-network.service lumonas-privd-power.service lumonas-privd-general.service; do
	[ -f "$SYSTEMD/$unit" ] || { echo "missing systemd unit: $unit" >&2; exit 1; }
	require_line "$SYSTEMD/$unit" 'NoNewPrivileges=true'
	require_line "$SYSTEMD/$unit" 'ProtectSystem=strict'
	require_line "$SYSTEMD/$unit" 'MemoryMax='
	require_line "$SYSTEMD/$unit" 'TasksMax='
	require_line "$SYSTEMD/$unit" 'Group=lumonas'
done

for target in lumonas-jobs.target lumonas-services.target lumonas-storage.target; do
	[ -f "$SYSTEMD/$target" ] || { echo "missing systemd target: $target" >&2; exit 1; }
	done

for key in NoNewPrivileges=true ProtectSystem=strict MemoryMax= TasksMax= Group=lumonas; do
	require_line "$SYSTEMD/lumonas-runtime.service" "$key"
done
require_line "$SYSTEMD/lumonas-runtime.service" 'PrivateTmp=false'

require_line "$SYSTEMD/lumonas-web.service" 'User=lumonas'
require_line "$SYSTEMD/lumonasd.service" 'User=lumonas'
require_line "$SYSTEMD/lumonas-privd.service" 'User=root'
require_line "$SYSTEMD/lumonas-privd.service" 'CapabilityBoundingSet='
require_line "$SYSTEMD/lumonasd.service" 'ReadWritePaths=/var/lib/lumonas /srv/lumonas'
require_line "$SYSTEMD/lumonasd.service" 'PartOf=lumonas-jobs.target'
require_line "$SYSTEMD/lumonas-web.service" 'PartOf=lumonas-services.target'
require_line "$SYSTEMD/smbd.service.d/lumonas.conf" 'PartOf=lumonas-services.target'
require_line "$SYSTEMD/rsync.service.d/lumonas.conf" 'PartOf=lumonas-services.target'
require_line "$SYSTEMD/vsftpd.service.d/lumonas.conf" 'PartOf=lumonas-services.target'
require_line "$SYSTEMD/docker.service.d/lumonas.conf" 'PartOf=lumonas-services.target'
require_line "$SYSTEMD/nfs-server.service.d/lumonas.conf" 'PartOf=lumonas-services.target'
require_line "$SYSTEMD/ssh.service.d/lumonas.conf" 'PartOf=lumonas-services.target'
require_line "$SYSTEMD/avahi-daemon.service.d/lumonas.conf" 'PartOf=lumonas-services.target'
require_line "$SYSTEMD/lumonasd.service" 'Requires=lumonas-privd.service lumonas-privd-storage.service lumonas-privd-network.service lumonas-privd-power.service lumonas-privd-general.service'
for worker in storage network power general; do
  require_line "$SYSTEMD/lumonas-privd-$worker.service" 'Requires=lumonas-privd.service'
done
require_line "$SYSTEMD/lumonas-privd-storage.service" 'CapabilityBoundingSet=CAP_SYS_ADMIN CAP_SYS_RAWIO'
require_line "$SYSTEMD/lumonas-privd-network.service" 'CapabilityBoundingSet=CAP_NET_ADMIN'
require_line "$SYSTEMD/lumonas-privd-power.service" 'CapabilityBoundingSet=CAP_SYS_BOOT'
require_line "$SYSTEMD/lumonas-privd-general.service" 'CapabilityBoundingSet=CAP_CHOWN CAP_DAC_OVERRIDE CAP_FOWNER CAP_SETGID CAP_SETUID'
require_line "$SYSTEMD/lumonas-privd-general.service" '/etc/exports.d /etc/ssh/sshd_config.d'
require_line "$SYSTEMD/lumonas-runtime.service" 'EnvironmentFile=-/etc/lumonas/runtime.env'
require_line "$SYSTEMD/lumonas-runtime.service" 'ExecStart=/usr/lib/lumonas/lumonas-privd --runtime'
require_line "$SYSTEMD/lumonas-runtime.service" 'CapabilityBoundingSet=CAP_SYS_ADMIN CAP_SYS_MODULE CAP_SYS_RESOURCE'

require_line "$ROOT/packaging/debian/postinst" 'useradd --system'
require_line "$ROOT/packaging/debian/postinst" '/var/lib/lumonas/secrets'
require_line "$ROOT/packaging/debian/postinst" '/etc/lumonas/lumonasd.env'
require_line "$ROOT/packaging/debian/postinst" 'LUMONAS_WEB_ROOT=/usr/share/lumonas/web'
require_line "$ROOT/packaging/debian/postinst" 'LUMONAS_WEB_LISTEN=0.0.0.0:8081'
require_line "$ROOT/packaging/debian/postinst" '/etc/lumonas/tls/server.key'
require_line "$ROOT/packaging/debian/postinst" 'failed to provision the web TLS certificate'
require_line "$ROOT/packaging/debian/postinst" 'web TLS certificate pair is incomplete'
require_line "$ROOT/packaging/build-deb.sh" 'build-manifest.json'
require_line "$ROOT/packaging/build-deb.sh" 'sourceDateEpoch'
require_line "$ROOT/installer/build-iso.sh" 'SOURCE_DATE_EPOCH'
require_line "$ROOT/installer/build-iso.sh" 'date -u -R -d'
require_line "$ROOT/packaging/build-deb.sh" 'daemon.json.lumonas'
require_line "$ROOT/packaging/debian/postinst" '/etc/docker/daemon.json'
require_line "$ROOT/packaging/docker-daemon.json" '"max-size": "10m"'
require_line "$ROOT/packaging/docker-daemon.json" '"max-file": "3"'
require_line "$ROOT/packaging/debian/postinst" 'lumonas-privd.service'
require_line "$ROOT/packaging/debian/postinst" 'LUMONAS_ZRAM_ENABLED=false'
require_line "$ROOT/packaging/debian/control" 'Depends: libc6, systemd, openssl'
require_line "$ROOT/packaging/debian/lumonas-web.env.example" 'LUMONAS_WEB_LISTEN=0.0.0.0:8081'
require_line "$ROOT/scripts/upgrade-service-order-smoke.sh" 'lumonas-runtime.service'
require_line "$ROOT/scripts/release-artifacts.sh" 'sha256sum "$artifact"'
require_line "$ROOT/scripts/release-artifacts.sh" 'RELEASE-MANIFEST.json'
require_line "$ROOT/scripts/release-artifacts.sh" 'RELEASE-MANIFEST.json; do'
require_line "$ROOT/scripts/release-artifacts.sh" 'sidecar(path.with_name'
require_line "$ROOT/scripts/verify-release.sh" 'release manifest {key} checksum mismatch'
require_line "$ROOT/scripts/verify-release.sh" 'release SBOM is missing SPDX document sections'
require_line "$ROOT/scripts/release-artifacts-smoke.sh" 'tampered SBOM sidecar was accepted'
require_line "$ROOT/scripts/release-artifacts-smoke.sh" 'malformed SBOM sidecar was accepted'
require_line "$ROOT/scripts/verify-release.sh" 'release manifest is not valid JSON'
require_line "$ROOT/scripts/verify-release.sh" 'release manifest artifact set does not match release directory'
require_line "$ROOT/scripts/verify-release.sh" 'artifact name is not a direct file name'
require_line "$ROOT/scripts/release-artifacts-smoke.sh" 'artifact outside the release directory'
require_line "$ROOT/scripts/verify-release.sh" 'LUMONAS_EXPECTED_SOURCE_COMMIT'
require_line "$ROOT/scripts/verify-release.sh" 'LUMONAS_EXPECTED_SOURCE_DATE_EPOCH'
require_line "$ROOT/.github/workflows/ci.yml" 'LUMONAS_EXPECTED_SOURCE_COMMIT: ${{ github.sha }}'
require_line "$ROOT/.github/workflows/ci.yml" 'git show -s --format=%ct'
require_line "$ROOT/scripts/release-artifacts-smoke.sh" 'verify-release.sh'
require_line "$ROOT/scripts/release-gate-policy-smoke.sh" 'race-fuzz'
require_line "$ROOT/scripts/release-gate-policy-smoke.sh" 'upgrade-compatibility'
require_line "$ROOT/scripts/release-gate-policy-smoke.sh" 'TestPublishActorSetsEventEnvelopeWithoutPayloadMutation'
require_line "$ROOT/scripts/installer-signature-policy-smoke.sh" 'LUMONAS_REPO_SIGN_KEY is required'
require_line "$ROOT/scripts/postinst-policy-smoke.sh" 'live systemd postinst still ignores service start failures'
require_line "$ROOT/Makefile" 'postinst-policy-smoke:'
require_line "$ROOT/packaging/debian/prerm" 'systemd host must not continue an upgrade'
require_line "$ROOT/packaging/debian/prerm" 'systemctl stop "$unit"'
require_line "$ROOT/scripts/permission-smoke.sh" '/etc/lumonas/runtime.env'
require_line "$ROOT/scripts/qemu-build-image.sh" 'lumonas-runtime.service'
require_line "$ROOT/scripts/qemu-build-image.sh" 'qemu-package-manifest.txt'
require_line "$ROOT/scripts/qemu-build-image.sh" 'dpkg-query -W'
require_line "$ROOT/scripts/qemu-build-image.sh" 'sourceCommit=$LUMONAS_SOURCE_COMMIT'
require_line "$ROOT/scripts/qemu-build-image.sh" 'snapshot.debian.org/archive/debian/20260201T000000Z'
require_line "$ROOT/scripts/qemu-build-image.sh" 'Acquire::Check-Valid-Until'
require_line "$ROOT/scripts/qemu-build-image.sh" 'LUMONAS_DEBIAN_MIRROR must use HTTPS'
require_line "$ROOT/installer/build-iso.sh" 'snapshot.debian.org/archive/debian/20260201T000000Z'
require_line "$ROOT/installer/build-iso.sh" 'Acquire::Check-Valid-Until=false'
require_line "$ROOT/installer/build-iso.sh" 'LUMONAS_DEBIAN_MIRROR must use HTTPS'
require_line "$ROOT/installer/build-iso.sh" 'LUMONAS_ISO_WORKDIR must be an absolute path'
require_line "$ROOT/installer/build-iso.sh" 'LUMONAS_ISO_CACHE_SOURCE must not be inside the ISO workdir'
require_line "$ROOT/scripts/installer-workdir-policy-smoke.sh" 'assert_rejected'
require_line "$ROOT/.github/workflows/ci.yml" 'bash scripts/installer-workdir-policy-smoke.sh'
require_line "$ROOT/cmd/lumonasd/share_configs.go" '/etc/lumonas/tls/server.crt'
require_line "$ROOT/cmd/lumonasd/share_configs.go" '/etc/lumonas/tls/server.key'
require_line "$ROOT/cmd/lumonasd/identity_provisioning.go" 'func (s *apiServer) rollbackNetworkCheckpoint'
require_line "$ROOT/cmd/lumonasd/main.go" 'recordNetworkCheckpointFn'
require_line "$ROOT/cmd/lumonasd/network_api.go" 'checkpoint persistence failed; checkpoint rolled back'
require_line "$ROOT/cmd/lumonasd/network_api_test.go" 'TestNetworkCheckpointRollsBackWhenPersistenceFails'
require_line "$ROOT/cmd/lumonasd/network_api_test.go" 'TestNetworkCheckpointActionReportsCompletionPersistenceFailure'
require_line "$ROOT/cmd/lumonasd/main_test.go" 'TestStorageConfirmationReportsPlanPersistenceFailure'
require_line "$ROOT/.github/workflows/ci.yml" 'TestStorageConfirmationReportsPlanPersistenceFailure'
require_line "$ROOT/cmd/lumonasd/main.go" 'network.wireguard.apply'
require_line "$ROOT/cmd/lumonas-privd/main.go" 'network.wireguard.apply'
require_line "$ROOT/cmd/lumonas-privd/worker_test.go" 'TestWireGuardMutationUsesNetworkWorkerAndTypedConfig'
require_line "$ROOT/cmd/lumonasd/network_api_test.go" 'TestWireGuardApplyUsesPrivilegedBroker'
require_line "$ROOT/cmd/lumonasd/main.go" 'network.tailscale.up'
require_line "$ROOT/cmd/lumonas-privd/main.go" 'network.tailscale.exit-node'
require_line "$ROOT/cmd/lumonas-privd/worker_test.go" 'TestTailscaleMutationUsesNetworkWorker'
require_line "$ROOT/cmd/lumonasd/network_api_test.go" 'TestTailscaleUpUsesPrivilegedBroker'
require_line "$ROOT/internal/network/tailscale.go" '--authkey=file:'
require_line "$ROOT/internal/network/tailscale_test.go" 'staged auth key still exists'
require_line "$ROOT/cmd/lumonasd/shutdown_api_test.go" 'TestShutdownPowerUsesPrivilegedBroker'
if rg -n 'privileged\.Client\{.*\}\.Execute' "$ROOT/cmd/lumonasd" --glob '*.go' --glob '!identity_provisioning.go' --glob '!*_test.go' >/dev/null 2>&1; then
	echo "lumonasd domain code must use executePrivileged instead of direct socket clients" >&2
	exit 1
fi
require_line "$ROOT/scripts/security-smoke.sh" 'TestNetworkCheckpointRollsBackWhenPersistenceFails'
if grep -F '/etc/lumonas/tls/tls.crt' "$ROOT/cmd/lumonasd/share_configs.go" >/dev/null 2>&1 || grep -F '/etc/lumonas/tls/tls.key' "$ROOT/cmd/lumonasd/share_configs.go" >/dev/null 2>&1; then
	echo "share configuration still references obsolete FTPS certificate paths" >&2
	exit 1
fi
require_line "$ROOT/packaging/debian/prerm" 'lumonas-web.service'
require_line "$ROOT/packaging/debian/prerm" 'lumonas-storage.target'
require_line "$ROOT/packaging/build-deb.sh" 'DEBIAN/prerm'
require_line "$ROOT/scripts/verify-deb.sh" 'lumonas-jobs.target'
require_line "$ROOT/scripts/verify-deb.sh" 'docker.service.d/lumonas.conf'
require_line "$ROOT/scripts/api-smoke.sh" 'start_server()'
require_line "$ROOT/scripts/api-smoke.sh" 'start_privileged_stack()'
require_line "$ROOT/scripts/api-smoke.sh" 'LUMONAS_PRIVD_SOCKET="$PRIVD_DIR/privd.sock"'
require_line "$ROOT/scripts/api-smoke.sh" 'updates/apply'
require_line "$ROOT/scripts/api-smoke.sh" 'api smoke rollback'
require_line "$ROOT/Makefile" 'update-fixture:'
require_line "$ROOT/cmd/lumonas-update-fixture/main.go" 'ed25519.Sign'
require_line "$ROOT/scripts/qemu-smoke.sh" 'LUMONAS_QEMU_UPDATE_ASSERT'
require_line "$ROOT/scripts/qemu-smoke.sh" 'qemu smoke rollback'
require_line "$ROOT/scripts/qemu-smoke.sh" 'if curl -kfsS -X POST -H'
require_line "$ROOT/scripts/qemu-build-image.sh" 'LUMONAS_UPDATE_FIXTURE'
require_line "$ROOT/scripts/qemu-build-image.sh" 'update-fixture/package'
require_line "$ROOT/scripts/qemu-build-image.sh" 'chown -R lumonas:lumonas /var/lib/lumonas/update-fixture'
require_line "$ROOT/.github/workflows/ci.yml" 'go-version: '\''1.26.x'\'''
require_line "$ROOT/.github/workflows/ci.yml" './cmd/lumonas-update-fixture'
require_line "$ROOT/scripts/api-smoke.sh" 'daemon restarted before the job completed'
require_line "$ROOT/scripts/api-smoke.sh" 'Last-Event-ID'
require_line "$ROOT/scripts/api-smoke.sh" 'validate-api-response.py'
require_line "$ROOT/scripts/api-smoke.sh" '/api/v1/system/metrics/history'
require_line "$ROOT/scripts/api-smoke.sh" '/api/v1/ups/config'
require_line "$ROOT/scripts/qemu-smoke.sh" '"privilegedBroker":true'
require_line "$ROOT/scripts/qemu-recovery-smoke.sh" '"privilegedBroker":true'
require_line "$ROOT/scripts/iso-smoke.sh" '"privilegedBroker":true'
require_line "$ROOT/scripts/qemu-live-recovery-source.sh" '"privilegedBroker":true'
require_line "$ROOT/Makefile" 'qemu-smoke: qemu-image'
require_line "$ROOT/Makefile" 'qemu-recovery-smoke: iso recovery-fixture'
require_line "$ROOT/Makefile" 'qemu-recovery-live: iso qemu-image'
require_line "$ROOT/Makefile" 'iso-smoke: iso'
require_line "$ROOT/Makefile" 'LUMONAS_ISO ?= $(CURDIR)/build/releases/lumonas-$(VERSION)-amd64.iso'
require_line "$ROOT/Makefile" 'LUMONAS_QEMU_IMAGE ?= $(CURDIR)/build/qemu/lumonas-debian13.raw'
require_line "$ROOT/.github/workflows/ci.yml" 'if: always()'
require_line "$ROOT/.github/workflows/ci.yml" 'name: lumonas-qemu'
require_line "$ROOT/.github/workflows/ci.yml" 'name: lumonas-iso-smoke'
require_line "$ROOT/scripts/validate-api-response.py" 'validate_metrics'
require_line "$ROOT/scripts/validate-api-response.py" 'validate_metrics_history'
require_line "$ROOT/scripts/validate-api-response.py" 'validate_events'
require_line "$ROOT/scripts/validate-sse.py" 'validate_events(events)'
require_line "$ROOT/cmd/lumonasd/main.go" 'endpoint == "/events"'
require_line "$ROOT/cmd/lumonasd/main.go" 'endpoint == "/events/stream"'
require_line "$ROOT/cmd/lumonasd/sse_route_test.go" 'TestEventStreamCompatibilityRoutes'
require_line "$ROOT/docs/openapi.yaml" 'eventStreamCompatibility'
require_line "$ROOT/web/src/api/events.ts" "EVENT_STREAM_PATH = '/api/v1/events/stream'"
require_line "$ROOT/scripts/qemu-smoke.sh" 'validate-sse.py'
require_line "$ROOT/scripts/qemu-smoke.sh" 'metrics-history'
require_line "$ROOT/cmd/lumonasd/job_admission.go" 'jobResourceKey'
require_line "$ROOT/cmd/lumonasd/job_admission_test.go" 'TestAdmitJobRejectsConflictingActiveResource'
require_line "$ROOT/scripts/api-smoke.sh" 'SSE replay returned the Last-Event-ID cursor event twice'
require_line "$ROOT/cmd/lumonasd/sse_replay_test.go" 'SSE response lost operation tracing fields'
require_line "$ROOT/internal/backup/destinations.go" 'func syncDirectory'
require_line "$ROOT/internal/backup/destinations.go" 'temporary.Sync()'
require_line "$ROOT/internal/backup/destinations_test.go" 'TestLocalUploadPublishesDurableMode0600Copy'
require_line "$ROOT/internal/updates/updates.go" 'func syncDirectory'
require_line "$ROOT/internal/updates/updates.go" 'output.Sync()'
require_line "$ROOT/internal/updates/updates_test.go" 'staged package is not durable/readable'
require_line "$ROOT/installer/build-iso.sh" 'dpkg-scanpackages'
require_line "$ROOT/installer/build-iso.sh" 'lumonas-local.list'
require_line "$ROOT/installer/build-iso.sh" 'LUMONAS_WEB_LISTEN=0.0.0.0:8081'
require_line "$ROOT/installer/build-iso.sh" 'LUMONAS_WEB_TLS_CERT=/etc/lumonas/tls/server.crt'
require_line "$ROOT/installer/build-iso.sh" 'LUMONAS_WEB_TLS_KEY=/etc/lumonas/tls/server.key'
require_line "$ROOT/installer/build-iso.sh" 'LUMONAS_COOKIE_SECURE=true'
require_line "$ROOT/installer/build-iso.sh" 'iso-package-manifest.txt'
require_line "$ROOT/installer/build-iso.sh" 'sourceDateEpoch=$SOURCE_DATE_EPOCH'
require_line "$ROOT/installer/build-iso.sh" 'dpkg-query -W'
require_line "$ROOT/installer/build-iso.sh" 'sourceCommit=$SOURCE_COMMIT'
require_line "$ROOT/installer/build-iso.sh" 'LUMONAS_ENABLE_RECOVERY_SMOKE'
require_line "$ROOT/installer/build-iso.sh" 'apt-ftparchive'
require_line "$ROOT/installer/build-iso.sh" 'InRelease'
require_line "$ROOT/installer/build-iso.sh" 'signed-by=/usr/share/keyrings/lumonas-archive-keyring.gpg'
require_line "$ROOT/installer/build-iso.sh" 'etc/apt/preferences.d/lumonas'
require_line "$ROOT/installer/build-iso.sh" 'Pin-Priority: 1001'
require_line "$ROOT/installer/build-iso.sh" 'LUMONAS_REPO_SIGN_KEY'
require_line "$ROOT/installer/build-iso.sh" 'LUMONAS_REQUIRE_REPO_SIGNATURE'
require_line "$ROOT/installer/build-iso.sh" 'signed LumoNAS repository metadata could not be verified'
require_line "$ROOT/installer/build-iso.sh" 'signed LumoNAS repository package installation failed'
require_line "$ROOT/installer/build-iso.sh" 'test -s InRelease'
require_line "$ROOT/.github/workflows/ci.yml" 'LUMONAS_REPO_PRIVATE_KEY'
require_line "$ROOT/.github/workflows/ci.yml" 'gpg --batch --import'
require_line "$ROOT/scripts/qemu-smoke.sh" '<title>LumoNAS</title>'
require_line "$ROOT/scripts/qemu-smoke.sh" '<div id="root"></div>'
require_line "$ROOT/scripts/qemu-smoke.sh" 'snapshot_disk_identities'
require_line "$ROOT/scripts/qemu-smoke.sh" 'device reorder did not change any transient device path'
require_line "$ROOT/scripts/qemu-smoke.sh" '"tmpfs"'
require_line "$ROOT/scripts/qemu-smoke.sh" 'lumonas-runtime.service'
require_line "$ROOT/scripts/frontend-runtime-smoke.sh" 'production frontend bundle contains the MSW bootstrap'
require_line "$ROOT/web/package.json" '"test:e2e": "playwright test"'
require_line "$ROOT/web/playwright.config.ts" 'VITE_USE_MOCKS'
require_line "$ROOT/web/e2e/smoke.spec.ts" 'lumonas-onboarded'
require_line "$ROOT/.github/workflows/ci.yml" 'frontend-e2e:'
require_line "$ROOT/.github/workflows/ci.yml" 'frontend-live-e2e:'
require_line "$ROOT/.github/workflows/ci.yml" 'pnpm exec playwright install --with-deps chromium'
require_line "$ROOT/Makefile" 'frontend-e2e:'
require_line "$ROOT/Makefile" 'frontend-live-e2e:'
require_line "$ROOT/web/package.json" '"test:e2e:live": "playwright test --config=playwright.live.config.ts"'
require_line "$ROOT/web/playwright.live.config.ts" 'VITE_USE_MOCKS'
require_line "$ROOT/web/playwright.live.config.ts" 'bash ../scripts/dev.sh full'
require_line "$ROOT/web/e2e/live.spec.ts" 'navigator.serviceWorker.controller'
for worker in storage network power general; do
  require_line "$ROOT/scripts/qemu-smoke.sh" "lumonas-privd-$worker.service"
done
[ -x "$ROOT/scripts/storage-loopback-smoke.sh" ] || { echo "storage loopback smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/privileged-storage-loopback-smoke.sh" ] || { echo "privileged storage loopback smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/disk-full-smoke.sh" ] || { echo "disk-full smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/disk-identity-smoke.sh" ] || { echo "disk-identity smoke test must be executable" >&2; exit 1; }
require_line "$ROOT/scripts/disk-identity-smoke.sh" 'DisksPromoteMountedPartitionMetadata'
require_line "$ROOT/internal/collector/disks.go" 'inheritFilesystemMetadata'
[ -x "$ROOT/scripts/fuzz-smoke.sh" ] || { echo "fuzz smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/request-limits-smoke.sh" ] || { echo "request-limits smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/retention-smoke.sh" ] || { echo "retention smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/generation-retention-smoke.sh" ] || { echo "generation retention smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/share-protocol-smoke.sh" ] || { echo "share protocol smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/frontend-runtime-smoke.sh" ] || { echo "frontend runtime smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/share-config-smoke.sh" ] || { echo "share configuration smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/iso-smoke.sh" ] || { echo "ISO smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/qemu-recovery-smoke.sh" ] || { echo "QEMU recovery smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/qemu-live-recovery-source.sh" ] || { echo "live recovery source helper must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/recovery-api-smoke.sh" ] || { echo "recovery API smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/recovery-bundle-smoke.sh" ] || { echo "recovery bundle smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/recovery-persistence-smoke.sh" ] || { echo "recovery persistence smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/security-smoke.sh" ] || { echo "security smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/secret-scan-smoke.sh" ] || { echo "secret scan smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/command-boundary-smoke.sh" ] || { echo "command-boundary smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/systemd-smoke.sh" ] || { echo "systemd smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/systemd-security-smoke.sh" ] || { echo "systemd security smoke test must be executable" >&2; exit 1; }
require_line "$ROOT/Makefile" 'storage-loopback:'
require_line "$ROOT/internal/storage/plans.go" 'invalid state must never appear as a confirmable plan'
require_line "$ROOT/internal/storage/plans.go" 'disk.erase does not accept requested state'
require_line "$ROOT/internal/httpobs/response.go" 'Flush keeps Server-Sent Events'
require_line "$ROOT/cmd/lumonasd/main.go" '"http request"'
require_line "$ROOT/Makefile" 'disk-full-smoke:'
require_line "$ROOT/Makefile" 'disk-identity-smoke:'
require_line "$ROOT/Makefile" 'fuzz-smoke:'
require_line "$ROOT/Makefile" 'request-limits-smoke:'
require_line "$ROOT/Makefile" 'retention-smoke:'
require_line "$ROOT/scripts/retention-smoke.sh" 'PruneOperationalHistoryBoundsCoreHistoryTables'
require_line "$ROOT/Makefile" 'generation-retention-smoke:'
require_line "$ROOT/Makefile" 'share-protocol-smoke:'
require_line "$ROOT/.github/workflows/ci.yml" 'LUMONAS_FUZZ_TIME=5s bash scripts/race-fuzz-smoke.sh'
require_line "$ROOT/scripts/fuzz-smoke.sh" 'FuzzValidateGeneratedShareConfigs'
require_line "$ROOT/scripts/fuzz-smoke.sh" 'FuzzStoragePlanValidation'
require_line "$ROOT/scripts/race-fuzz-smoke.sh" 'go test -race'
require_line "$ROOT/scripts/race-fuzz-smoke.sh" 'go test -race ./...'
require_line "$ROOT/.github/workflows/ci.yml" 'LUMONAS_FUZZ_TIME=5s bash scripts/race-fuzz-smoke.sh'
[ -x "$ROOT/scripts/race-fuzz-smoke.sh" ] || { echo "race and fuzz smoke test must be executable" >&2; exit 1; }
require_line "$ROOT/scripts/fuzz-smoke.sh" 'FuzzNetworkConnectionValidation'
require_line "$ROOT/Makefile" 'share-config-smoke:'
require_line "$ROOT/Makefile" 'qemu-recovery-smoke:'
require_line "$ROOT/Makefile" 'qemu-recovery-live:'
require_line "$ROOT/Makefile" 'recovery-fixture:'
require_line "$ROOT/Makefile" 'recovery-api-smoke:'
require_line "$ROOT/Makefile" 'security-smoke:'
require_line "$ROOT/Makefile" 'secret-scan-smoke:'
require_line "$ROOT/Makefile" 'systemd-smoke:'
require_line "$ROOT/Makefile" 'systemd-security-smoke:'
require_line "$ROOT/Makefile" 'permission-smoke:'
require_line "$ROOT/Makefile" 'log-retention-smoke:'
require_line "$ROOT/Makefile" 'log-identity-smoke:'
require_line "$ROOT/scripts/log-identity-smoke.sh" 'SyslogIdentifier='
require_line "$ROOT/.github/workflows/ci.yml" 'scripts/log-identity-smoke.sh'
[ -x "$ROOT/scripts/log-identity-smoke.sh" ] || { echo "log identity smoke test must be executable" >&2; exit 1; }
require_line "$ROOT/Makefile" 'check-api-contract:'
require_line "$ROOT/scripts/check-api-contract.py" 'frontend response types are missing from OpenAPI schemas'
require_line "$ROOT/scripts/check-openapi-duplicates.py" 'duplicate path'
require_line "$ROOT/Makefile" 'upgrade-smoke:'
require_line "$ROOT/Makefile" 'race-fuzz:'
require_line "$ROOT/Makefile" 'upgrade-compatibility:'
require_line "$ROOT/.github/workflows/ci.yml" 'TestOpenMigratesLegacyBackupRunActorColumn'
require_line "$ROOT/Makefile" 'release-gate-policy:'
[ -x "$ROOT/scripts/upgrade-smoke.sh" ] || { echo "upgrade smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/upgrade-service-order-smoke.sh" ] || { echo "upgrade service ordering smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/release-artifacts-smoke.sh" ] || { echo "release artifact smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/release-gate-policy-smoke.sh" ] || { echo "release gate policy smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/installer-signature-policy-smoke.sh" ] || { echo "installer signature policy smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/permission-smoke.sh" ] || { echo "permission smoke test must be executable" >&2; exit 1; }
[ -x "$ROOT/scripts/log-retention-smoke.sh" ] || { echo "log retention smoke test must be executable" >&2; exit 1; }
require_line "$ROOT/packaging/build-deb.sh" 'cmd/lumonas-recover'
require_line "$ROOT/packaging/build-deb.sh" 'cmd/lumonas-migrate'
require_line "$ROOT/packaging/build-deb.sh" 'touch -h --date="@$SOURCE_DATE_EPOCH"'
require_line "$ROOT/scripts/reproducible-package-smoke.sh" 'repeated Debian package builds differ'
require_line "$ROOT/.github/workflows/ci.yml" 'LUMONAS_GIT_COMMIT="$GITHUB_SHA" make package'
[ -x "$ROOT/scripts/reproducible-package-smoke.sh" ] || { echo "reproducible package smoke test must be executable" >&2; exit 1; }
require_line "$ROOT/packaging/debian/postinst" 'lumonas-migrate'
require_line "$ROOT/packaging/debian/postinst" 'runuser -u lumonas'
require_line "$ROOT/packaging/debian/control" 'avahi-daemon'
require_line "$ROOT/cmd/lumonas-web/main.go" 'X-Forwarded-Proto'
require_line "$ROOT/cmd/lumonas-web/main_test.go" 'TestHandlerMarksHTTPSProxyRequestsAndStaticResponses'
require_line "$ROOT/scripts/package-dependency-parity-smoke.sh" 'no-install-recommends'
require_line "$ROOT/Makefile" 'package-dependency-parity:'
require_line "$ROOT/Makefile" 'iso: package'
require_line "$ROOT/Makefile" 'qemu-image: package'
require_line "$ROOT/.github/workflows/ci.yml" 'LUMONAS_GIT_COMMIT="$GITHUB_SHA" make package'
require_line "$ROOT/.github/workflows/ci.yml" 'scripts/package-dependency-parity-smoke.sh'
require_line "$ROOT/packaging/debian/control" 'vsftpd'
require_line "$ROOT/packaging/debian/control" 'xfsprogs'
require_line "$ROOT/packaging/debian/control" 'mergerfs'
require_line "$ROOT/packaging/debian/control" 'snapraid'
require_line "$ROOT/scripts/storage-loopback-smoke.sh" 'MISMATCH_LOOP=$LAST_LOOP'
require_line "$ROOT/scripts/storage-loopback-smoke.sh" 'wipefs --all --force'
require_line "$ROOT/scripts/storage-loopback-smoke.sh" 'snapraid -c "$SNAPRAID_CONFIG" sync'
require_line "$ROOT/cmd/lumonasd/network_api.go" 'firewall.apply'
require_line "$ROOT/cmd/lumonasd/network_api.go" 'ExpiresAt: time.Now().UTC().Add(2 * time.Minute)'
require_line "$ROOT/cmd/lumonas-privd/main.go" '"firewall.apply"'
require_line "$ROOT/cmd/lumonas-privd/main_test.go" 'TestFirewallApplyRequiresOperationID'
require_line "$ROOT/cmd/lumonas-privd/main_test.go" 'TestRemainingMutationsRequireOperationID'
require_line "$ROOT/cmd/lumonasd/share_configs.go" 's.brokerExecute(ctx, privileged.Request'
require_line "$ROOT/cmd/lumonasd/share_configs.go" 'ExpiresAt: time.Now().UTC().Add(2 * time.Minute)'
require_line "$ROOT/cmd/lumonasd/share_configs_test.go" 'TestReloadShareServicesFailsClosedWithoutPrivilegedBroker'
require_line "$ROOT/cmd/lumonas-privd/main.go" '"service.config.apply", "avahi.config.apply"'
require_line "$ROOT/cmd/lumonasd/identity_provisioning.go" 'OperationID:    newID("identity")'
require_line "$ROOT/cmd/lumonasd/identity_provisioning.go" 'OperationID:    newID("samba")'
require_line "$ROOT/cmd/lumonas-privd/main.go" '"identity.system-user.ensure", "samba.user.ensure", "acl.apply"'
require_line "$ROOT/internal/privileged/limits.go" 'MaxIPCMessageBytes = 1 << 20'
require_line "$ROOT/internal/privileged/client.go" 'io.LimitReader(connection, MaxIPCMessageBytes)'
require_line "$ROOT/cmd/lumonas-privd/main.go" 'scanner.Buffer(make([]byte, 64*1024), privileged.MaxIPCMessageBytes)'
require_line "$ROOT/cmd/lumonas-privd/main.go" 'io.LimitReader(connection, privileged.MaxIPCMessageBytes)'
require_line "$ROOT/internal/privileged/client_test.go" 'TestClientRejectsOversizedResponse'
require_line "$ROOT/internal/privileged/client_test.go" 'TestClientRejectsOversizedRequestBeforeWriting'
require_line "$ROOT/cmd/lumonas-privd/worker_test.go" 'TestBrokerRejectsOversizedWorkerResponse'
require_line "$ROOT/cmd/lumonasd/main.go" 'disk identity export failed'
require_line "$ROOT/cmd/lumonasd/main.go" 'NAS identity is not configured'
require_line "$ROOT/cmd/lumonasd/main.go" 'Docker stack export failed'
require_line "$ROOT/internal/recovery/persist.go" 'publish versioned recovery bundle'
require_line "$ROOT/cmd/lumonasd/recovery_export_safety_test.go" 'TestRecoveryExportFailsClosedWhenDiskIdentityCollectionFails'
require_line "$ROOT/cmd/lumonasd/recovery_export_safety_test.go" 'TestRecoveryExportRequiresNASIdentity'
require_line "$ROOT/scripts/recovery-api-smoke.sh" 'TestRecoveryExportRequiresNASIdentity'
require_line "$ROOT/scripts/recovery-bundle-smoke.sh" 'ReadBundleFilesRejectsTooManyZipEntries'
require_line "$ROOT/scripts/recovery-persistence-smoke.sh" 'TestPersistVerified'
require_line "$ROOT/internal/recovery/persist.go" 'syncDirectory'
require_line "$ROOT/cmd/lumonasd/main.go" 'recovery.PersistVerified'
require_line "$ROOT/internal/recovery/bundle.go" 'MaxBundleExpandedBytes'
require_line "$ROOT/internal/recovery/bundle.go" 'io.LimitReader(handle, MaxBundleEntryBytes+1)'
require_line "$ROOT/Makefile" 'recovery-bundle-smoke:'
require_line "$ROOT/.github/workflows/ci.yml" 'TestClientRejectsOversizedResponse'
require_line "$ROOT/.github/workflows/ci.yml" 'TestBrokerRejectsOversizedWorkerResponse'
require_line "$ROOT/.github/workflows/ci.yml" 'TestRecoveryExportFailsClosedWhenDiskIdentityCollectionFails'
require_line "$ROOT/cmd/lumonasd/recovery_export_e2e_test.go" 'versioned recovery bundle was not verifiable'
require_line "$ROOT/internal/notify/providers.go" 'MaxProviderResponseBytes = 64 << 10'
require_line "$ROOT/internal/notify/providers.go" 'io.LimitReader(response.Body, MaxProviderResponseBytes+1)'
require_line "$ROOT/internal/notify/providers_test.go" 'TestSendChannelRejectsOversizedProviderResponse'
require_line "$ROOT/scripts/security-smoke.sh" 'TestSendChannelRejectsOversizedProviderResponse'
require_line "$ROOT/cmd/lumonasd/support_api.go" 'collectionErrors'
require_line "$ROOT/cmd/lumonasd/support_api_test.go" 'TestSupportBundleReportsUnavailableCollections'
require_line "$ROOT/scripts/security-smoke.sh" 'TestSupportBundleReportsUnavailableCollections'
require_line "$ROOT/cmd/lumonasd/main.go" 'notification credentials unavailable'
require_line "$ROOT/cmd/lumonasd/main.go" 'func (s *apiServer) saveNotificationDelivery'
require_line "$ROOT/cmd/lumonasd/notification_api_test.go" 'TestNotificationCredentialFailureIsPersistedAsDeliveryFailure'
require_line "$ROOT/scripts/security-smoke.sh" 'TestNotificationCredentialFailureIsPersistedAsDeliveryFailure'
require_line "$ROOT/cmd/lumonasd/notification_api.go" 'if !state.SuppressedUntil.IsZero()'
require_line "$ROOT/cmd/lumonasd/notification_api_test.go" 'TestNotificationFailureWindowAccumulatesBeforeSuppression'
require_line "$ROOT/scripts/security-smoke.sh" 'TestNotificationFailureWindowAccumulatesBeforeSuppression'
require_line "$ROOT/cmd/lumonasd/main.go" 's.notificationClient'
require_line "$ROOT/cmd/lumonasd/notification_api_test.go" 'TestConfiguredNotificationDeliveryUsesInjectedClient'
require_line "$ROOT/scripts/security-smoke.sh" 'TestConfiguredNotificationDeliveryUsesInjectedClient'
require_line "$ROOT/scripts/storage-loopback-smoke.sh" 'missing-snapraid.conf'
require_line "$ROOT/scripts/privileged-storage-loopback-smoke.sh" 'filesystem.format'
require_line "$ROOT/scripts/privileged-storage-loopback-smoke.sh" 'loop-mounted-erase'
require_line "$ROOT/scripts/privileged-storage-loopback-smoke.sh" 'loop-stale'
require_line "$ROOT/scripts/privileged-storage-loopback-smoke.sh" 'loop-expired'
require_line "$ROOT/scripts/privileged-storage-loopback-smoke.sh" 'operationId is required'
require_line "$ROOT/scripts/disk-full-smoke.sh" 'LUMONAS_DISK_FULL_ASSERT'
require_line "$ROOT/.github/workflows/ci.yml" 'disk-full:'
require_line "$ROOT/.github/workflows/ci.yml" 'privileged-storage-loopback:'
require_line "$ROOT/Makefile" 'privileged-storage-loopback:'
require_line "$ROOT/installer/build-iso.sh" 'xfsprogs'
require_line "$ROOT/scripts/qemu-build-image.sh" 'xfsprogs'
require_line "$ROOT/installer/build-iso.sh" 'vsftpd'
require_line "$ROOT/scripts/qemu-build-image.sh" 'NetworkManager.service'
require_line "$ROOT/scripts/qemu-build-image.sh" 'qemu-ethernet.nmconnection'
require_line "$ROOT/scripts/qemu-build-image.sh" 'openssl'
require_line "$ROOT/scripts/qemu-smoke.sh" 'https://127.0.0.1:18080'
require_line "$ROOT/scripts/iso-smoke.sh" 'https://127.0.0.1:18081'
require_line "$ROOT/scripts/qemu-recovery-smoke.sh" 'https://127.0.0.1:18082'
require_line "$ROOT/scripts/qemu-smoke.sh" 'restrict=on,hostfwd=tcp::18080-:8081'
require_line "$ROOT/scripts/iso-smoke.sh" 'restrict=on,hostfwd=tcp::18081-:8081'
require_line "$ROOT/scripts/qemu-recovery-smoke.sh" 'restrict=on,hostfwd=tcp::18082-:8081'
require_line "$ROOT/scripts/qemu-live-recovery-source.sh" 'restrict=on,hostfwd=tcp::18083-:8081'
require_line "$ROOT/scripts/qemu-recovery-smoke.sh" 'restrict=on,hostfwd=tcp::18084-:8081'
require_line "$ROOT/scripts/iso-smoke.sh" 'api/v1/services'
require_line "$ROOT/scripts/qemu-recovery-smoke.sh" 'recovered-services.json'
require_line "$ROOT/scripts/qemu-recovery-smoke.sh" 'config-generation.json'
require_line "$ROOT/scripts/qemu-recovery-smoke.sh" 'fuse.mergerfs'
require_line "$ROOT/scripts/qemu-recovery-smoke.sh" 'cmd/lumonas-recover'
require_line "$ROOT/scripts/qemu-recovery-smoke.sh" 'LUMONAS_RECOVER_BIN'
require_line "$ROOT/scripts/qemu-recovery-smoke.sh" 'LUMONAS_RECOVERY_SOURCE_IMAGE'
require_line "$ROOT/installer/build-iso.sh" 'grub-install --target=i386-pc'
require_line "$ROOT/installer/build-iso.sh" 'rsync -aHAX --numeric-ids --one-file-system'
require_line "$ROOT/installer/build-iso.sh" 'UUID=%s / ext4 defaults 0 1'
require_line "$ROOT/installer/build-iso.sh" '/mnt/lumonas-target/live/vmlinuz'
require_line "$ROOT/scripts/qemu-recovery-smoke.sh" 'recovered replacement disk did not boot a healthy API'
require_line "$ROOT/scripts/qemu-recovery-smoke.sh" 'wait "$QEMU_PID"'
require_line "$ROOT/scripts/qemu-live-recovery-source.sh" 'api/v1/recovery/export'
require_line "$ROOT/scripts/qemu-live-recovery-source.sh" 'SOURCE_API="https://127.0.0.1:18083"'
require_line "$ROOT/scripts/qemu-live-recovery-source.sh" 'curl -kfsS "$SOURCE_API/healthz"'
require_line "$ROOT/scripts/qemu-live-recovery-source.sh" 'SOURCE_COOKIES='
require_line "$ROOT/scripts/qemu-live-recovery-source.sh" 'SOURCE_CSRF='
require_line "$ROOT/scripts/qemu-live-recovery-source.sh" 'X-CSRF-Token: $SOURCE_CSRF'
require_line "$ROOT/scripts/qemu-live-recovery-source.sh" 'live recovery source shutdown request failed'
require_line "$ROOT/scripts/qemu-live-recovery-source.sh" 'live recovery source appliance did not power off cleanly'
require_line "$ROOT/scripts/qemu-live-recovery-source.sh" 'wait "$SOURCE_PID"'
require_line "$ROOT/scripts/qemu-live-recovery-source.sh" 'filesystem.create'
require_line "$ROOT/scripts/qemu-recovery-smoke.sh" 'LUMONAS_RECOVERY_DEBUG_DIR'
require_line "$ROOT/.github/workflows/ci.yml" 'build/qemu/recovery-debug/**'
require_line "$ROOT/scripts/qemu-live-recovery-source.sh" 'storage/pools/plan'
require_line "$ROOT/scripts/qemu-live-recovery-source.sh" 'api/v1/network/connections'
require_line "$ROOT/scripts/qemu-live-recovery-source.sh" 'mode: live-source'
require_line "$ROOT/scripts/qemu-recovery-smoke.sh" '"databaseValid":true'
require_line "$ROOT/scripts/qemu-recovery-smoke.sh" 'databaseRestored'
require_line "$ROOT/scripts/qemu-recovery-smoke.sh" 'secretsRestored'
require_line "$ROOT/cmd/lumonasd/onboarding_api.go" 'onboardingProtectionReady'
require_line "$ROOT/cmd/lumonasd/onboarding_api_test.go" 'TestOnboardingProtectionWaitsForMountedDisks'
require_line "$ROOT/cmd/lumonas-privd/main.go" 'could not verify target mount state'
require_line "$ROOT/cmd/lumonas-privd/main.go" 'MOUNTPOINT'
require_line "$ROOT/cmd/lumonas-privd/storage_safety_contract_test.go" 'TestDestructiveStorageExecutionDetectsMountedPartitionWithLsblk'
require_line "$ROOT/scripts/privileged-storage-loopback-smoke.sh" 'sfdisk --no-reread'
require_line "$ROOT/scripts/privileged-storage-loopback-smoke.sh" 'partx --update'
require_line "$ROOT/scripts/privileged-storage-loopback-smoke.sh" 'partition-mounted'
require_line "$ROOT/scripts/privileged-storage-loopback-smoke.sh" 'unstable-path'
require_line "$ROOT/scripts/privileged-storage-loopback-smoke.sh" 'no stable identity'
require_line "$ROOT/internal/storage/replacement.go" 'callers must resolve it against the live inventory'
require_line "$ROOT/internal/storage/replacement.go" 'replacement disks require stable identities'
require_line "$ROOT/cmd/lumonasd/replacement_api_test.go" 'resolved parity identity'
require_line "$ROOT/internal/storage/snapraid_config.go" 'has no stable identity'
require_line "$ROOT/internal/storage/snapraid_config.go" 'same branch path'
require_line "$ROOT/internal/storage/pool_setup.go" 'validatePoolSetupBranches'
require_line "$ROOT/installer/build-iso.sh" 'LUMONASD_LISTEN=127.0.0.1:18083'
require_line "$ROOT/installer/build-iso.sh" 'restored-principals.json'
require_line "$ROOT/installer/build-iso.sh" 'restored-shares.json'
require_line "$ROOT/installer/build-iso.sh" 'serial_LUMONAS-DATA1'
require_line "$ROOT/installer/build-iso.sh" 'FailureAction=poweroff'
require_line "$ROOT/scripts/qemu-recovery-smoke.sh" 'recovery guest did not power off before timeout'
require_line "$ROOT/docs/16_TESTING_CI_RELEASE_ENGINEERING.md" 'shared bounded runner'
require_line "$ROOT/docs/16_TESTING_CI_RELEASE_ENGINEERING.md" 'command-boundary policy smoke'
require_line "$ROOT/docs/16_TESTING_CI_RELEASE_ENGINEERING.md" 'privileged Unix-socket client'
require_line "$ROOT/scripts/qemu-build-image.sh" 'vsftpd'
for dropin in smbd.service.d/lumonas.conf rsync.service.d/lumonas.conf vsftpd.service.d/lumonas.conf; do
	[ -f "$ROOT/packaging/systemd/$dropin" ] || { echo "missing service drop-in: $dropin" >&2; exit 1; }
done
LUMONAS_REQUIRE_SYSTEMD_VERIFY="${LUMONAS_REQUIRE_SYSTEMD_VERIFY:-false}" \
	bash "$ROOT/scripts/systemd-smoke.sh"
LUMONAS_REQUIRE_SYSTEMD_SECURITY="${LUMONAS_REQUIRE_SYSTEMD_SECURITY:-false}" \
	bash "$ROOT/scripts/systemd-security-smoke.sh"
echo "LumoNAS packaging policy checks passed"
