import { useState, type FormEvent } from 'react'
import { CloudUpload, ExternalLink, Link2, Play, Plus, Trash2, TriangleAlert } from 'lucide-react'
import { useCancelSnapshotReplicationTask, useCreateSnapshotReplicationTask, useDeleteReplicationPeer, useDeleteSnapshotReplicationTask, useReplicationPeers, useRunReplicationPeer, useRunSnapshotReplicationTask, useSaveReplicationPeer, useServer, useShares, useSnapshotReplicationRuns, useSnapshotReplicationTasks, useUpdateSnapshotReplicationTask } from '@/api/queries'
import { AlertBanner } from '@/components/core/alert-banner'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { timeAgo } from '@/lib/format'
import type { ReplicationPeer } from '@/api/types'

function needsAttention(peer: ReplicationPeer) {
  const lastSync = peer.lastSyncAt ? Date.parse(peer.lastSyncAt) : Number.NaN
  return Boolean(peer.lastError) || !Number.isFinite(lastSync) || Date.now() - lastSync > 7 * 86_400_000
}

function SnapshotReplicationRunHistory({ taskId }: { taskId: string }) {
  const { data: runs } = useSnapshotReplicationRuns(taskId)
  if (!runs?.length) return <p className="mt-1 text-xs text-muted-foreground">No run history yet.</p>
  const latest = runs[0]
  return <p className="mt-1 text-xs text-muted-foreground">Latest run: {latest.state} · {latest.stage}{latest.state === 'running' ? ` · ${Math.round(latest.progress)}% · ${latest.bytes.toLocaleString()} bytes` : ''}{latest.error ? ` · ${latest.error}` : ''}</p>
}

export function ReplicationTab() {
  const { data: peers } = useReplicationPeers()
  const { data: localServer } = useServer()
  const { data: shares } = useShares()
  const { data: snapshotTasks } = useSnapshotReplicationTasks()
  const save = useSaveReplicationPeer(); const run = useRunReplicationPeer(); const remove = useDeleteReplicationPeer()
  const createSnapshotTask = useCreateSnapshotReplicationTask(); const updateSnapshotTask=useUpdateSnapshotReplicationTask(); const runSnapshotTask = useRunSnapshotReplicationTask(); const cancelSnapshotTask=useCancelSnapshotReplicationTask(); const deleteSnapshotTask = useDeleteSnapshotReplicationTask()
  const [open, setOpen] = useState(false); const [removeTarget, setRemoveTarget] = useState<ReplicationPeer | null>(null); const [name, setName] = useState(''); const [url, setURL] = useState(''); const [token, setToken] = useState(''); const [statusToken, setStatusToken] = useState('')
  const [taskName, setTaskName] = useState(''); const [taskPeerId, setTaskPeerId] = useState(''); const [sourceShareId, setSourceShareId] = useState(''); const [destinationShareId, setDestinationShareId] = useState(''); const [receiveToken, setReceiveToken] = useState(''); const [scheduleKind, setScheduleKind] = useState<'manual'|'daily'|'weekly'>('daily'); const [scheduleTime, setScheduleTime] = useState('02:00'); const [scheduleWeekday, setScheduleWeekday] = useState('sunday')
  const [editingTaskId,setEditingTaskId]=useState<string|null>(null)
  function submit(event: FormEvent) { event.preventDefault(); save.mutate({ name: name.trim(), url: url.trim(), token, statusToken: statusToken.trim() || undefined }, { onSuccess: () => { setOpen(false); setName(''); setURL(''); setToken(''); setStatusToken('') } }) }
  function clearTaskForm(){setEditingTaskId(null);setTaskName('');setTaskPeerId('');setSourceShareId('');setDestinationShareId('');setReceiveToken('');setScheduleKind('daily');setScheduleTime('02:00');setScheduleWeekday('sunday')}
  function submitSnapshotTask(event: FormEvent) { event.preventDefault(); if(editingTaskId){updateSnapshotTask.mutate({id:editingTaskId,name:taskName.trim(),scheduleKind,timeOfDay:scheduleTime,weekday:scheduleWeekday,receiveToken:receiveToken.trim()||undefined},{onSuccess:clearTaskForm})}else{createSnapshotTask.mutate({peerId:taskPeerId,name:taskName.trim(),sourceShareId,destinationShareId:destinationShareId.trim(),receiveToken,scheduleKind,timeOfDay:scheduleTime,weekday:scheduleWeekday},{onSuccess:clearTaskForm})} }
  const online = (peers ?? []).filter((peer) => peer.remoteStatus === 'online').length
  const attention = (peers ?? []).filter((peer) => peer.remoteStatus === 'offline' || needsAttention(peer) || Boolean(peer.lastError) || Boolean(peer.remoteVersion && localServer?.version && peer.remoteVersion !== localServer.version)).length
  return <div className="flex flex-col gap-4"><Card><CardHeader className="flex-row items-center justify-between space-y-0 pb-3"><CardTitle className="flex items-center gap-2 text-sm font-medium text-muted-foreground"><CloudUpload className="size-4" />LumoNAS fleet overview</CardTitle><Button size="sm" variant="outline" onClick={() => setOpen(true)}><Plus />Pair NAS</Button></CardHeader><CardContent><p className="text-sm text-muted-foreground">Copies the latest encrypted recovery bundle to another LumoNAS over HTTPS. The destination stores an offline replica; keep the recovery key separately.</p><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4"><div className="rounded-md border p-2"><p className="text-lg font-semibold tabular-nums">{peers?.length ?? 0}</p><p className="text-xs text-muted-foreground">Paired systems</p></div><div className="rounded-md border p-2"><p className="text-lg font-semibold tabular-nums">{online}</p><p className="text-xs text-muted-foreground">Online now</p></div><div className="rounded-md border p-2"><p className="text-lg font-semibold tabular-nums">{attention}</p><p className="text-xs text-muted-foreground">Need review</p></div><div className="rounded-md border p-2"><p className="text-lg font-semibold">30 sec</p><p className="text-xs text-muted-foreground">Status refresh</p></div></div></CardContent></Card>
    <Card><CardHeader><CardTitle className="text-sm">Btrfs snapshot replication</CardTitle><p className="text-sm text-muted-foreground">Send read-only snapshots to a dedicated share on another LumoNAS. The first run sends a full snapshot; later runs send incrementals. Create a destination token scoped to that share in Settings → Security → API tokens.</p></CardHeader><CardContent className="space-y-3">
      <form className="grid gap-3 rounded-lg border p-3 md:grid-cols-2" onSubmit={submitSnapshotTask}>
        {editingTaskId?<p className="text-sm font-medium md:col-span-2">Editing snapshot task</p>:null}
        <div className="space-y-1"><Label htmlFor="replica-task-name">Task name</Label><Input id="replica-task-name" value={taskName} onChange={(event)=>setTaskName(event.target.value)} placeholder="Documents to offsite NAS" /></div>
        {!editingTaskId?<><div className="space-y-1"><Label htmlFor="replica-task-peer">Remote NAS</Label><select id="replica-task-peer" value={taskPeerId} onChange={(event)=>setTaskPeerId(event.target.value)} className="h-9 w-full rounded-md border bg-background px-3 text-sm"><option value="">Choose paired NAS</option>{(peers??[]).map((peer)=><option key={peer.id} value={peer.id}>{peer.name} · {peer.remoteStatus??'checking'}</option>)}</select></div>
        <div className="space-y-1"><Label htmlFor="replica-task-source">Local Btrfs share</Label><select id="replica-task-source" value={sourceShareId} onChange={(event)=>setSourceShareId(event.target.value)} className="h-9 w-full rounded-md border bg-background px-3 text-sm"><option value="">Choose source share</option>{(shares??[]).map((share)=><option key={share.id} value={share.id}>{share.name}</option>)}</select></div>
        <div className="space-y-1"><Label htmlFor="replica-task-destination">Remote destination share ID</Label><Input id="replica-task-destination" value={destinationShareId} onChange={(event)=>setDestinationShareId(event.target.value)} placeholder="Paste the ID shown in the destination token scope" /></div></>:null}
        <div className="space-y-1 md:col-span-2"><Label htmlFor="replica-task-token">Destination snapshot receive token</Label><Input id="replica-task-token" type="password" autoComplete="off" value={receiveToken} onChange={(event)=>setReceiveToken(event.target.value)} placeholder={editingTaskId?'Leave blank to keep the saved token':'Paste the token created for the selected destination share'} /></div>
        <div className="space-y-1"><Label htmlFor="replica-task-schedule">Schedule</Label><select id="replica-task-schedule" value={scheduleKind} onChange={(event)=>setScheduleKind(event.target.value as typeof scheduleKind)} className="h-9 w-full rounded-md border bg-background px-3 text-sm"><option value="manual">Manual only</option><option value="daily">Daily</option><option value="weekly">Weekly</option></select></div>
        {scheduleKind!=='manual'?<div className="space-y-1"><Label htmlFor="replica-task-time">Run time (NAS local time)</Label><Input id="replica-task-time" type="time" value={scheduleTime} onChange={(event)=>setScheduleTime(event.target.value)} /></div>:null}
        {scheduleKind==='weekly'?<div className="space-y-1"><Label htmlFor="replica-task-weekday">Weekday</Label><select id="replica-task-weekday" value={scheduleWeekday} onChange={(event)=>setScheduleWeekday(event.target.value)} className="h-9 w-full rounded-md border bg-background px-3 text-sm">{['monday','tuesday','wednesday','thursday','friday','saturday','sunday'].map((day)=><option key={day} value={day}>{day[0]?.toUpperCase()+day.slice(1)}</option>)}</select></div>:null}
        <div className="flex items-end gap-2">{editingTaskId?<Button type="button" variant="ghost" onClick={clearTaskForm}>Cancel edit</Button>:null}<Button type="submit" disabled={!taskName.trim()||(editingTaskId?updateSnapshotTask.isPending:!taskPeerId||!sourceShareId||!destinationShareId.trim()||!receiveToken||createSnapshotTask.isPending)}>{editingTaskId?'Save changes':<><Plus/>Add snapshot task</>}</Button></div>
      </form>
      {(snapshotTasks??[]).length===0?<p className="rounded-md border border-dashed p-4 text-center text-sm text-muted-foreground">No snapshot replication tasks configured.</p>:<ul className="divide-y rounded-lg border">{snapshotTasks?.map((task)=><li key={task.id} className="flex flex-wrap items-center justify-between gap-3 p-3"><div className="min-w-0"><p className="flex flex-wrap items-center gap-2 text-sm font-medium">{task.name}<Badge variant={task.running?'warning':task.lastError?'destructive':'secondary'}>{task.running?'running':task.lastError?'failed':task.scheduleKind}</Badge></p><p className="mt-1 text-xs text-muted-foreground">{peers?.find((peer)=>peer.id===task.peerId)?.name??task.peerId} · {shares?.find((share)=>share.id===task.sourceShareId)?.name??task.sourceShareId} → {task.destinationShareId}{task.lastSyncAt?` · last success ${timeAgo(task.lastSyncAt)}`:' · not run yet'}{task.lastSnapshotName?` · ${task.lastSnapshotName}`:''}</p><SnapshotReplicationRunHistory taskId={task.id}/>{task.lastError?<p className="mt-1 text-xs text-destructive">{task.lastError}</p>:null}</div><div className="flex gap-2">{task.running?<Button size="sm" variant="outline" onClick={()=>cancelSnapshotTask.mutate(task.id)} disabled={cancelSnapshotTask.isPending}>Cancel run</Button>:<><Button size="sm" variant="ghost" onClick={()=>{setEditingTaskId(task.id);setTaskName(task.name);setTaskPeerId(task.peerId);setSourceShareId(task.sourceShareId);setDestinationShareId(task.destinationShareId);setScheduleKind(task.scheduleKind);setScheduleTime(task.timeOfDay);setScheduleWeekday(task.weekday??'sunday');setReceiveToken('')}}>Edit</Button><Button size="sm" variant="outline" onClick={()=>runSnapshotTask.mutate(task.id)} disabled={runSnapshotTask.isPending}><Play/>Run now</Button></>}<Button size="sm" variant="ghost" aria-label={`Delete ${task.name}`} className="text-destructive hover:text-destructive" onClick={()=>{if(window.confirm(`Remove snapshot task “${task.name}”? Snapshots already received on the remote NAS will remain.`))deleteSnapshotTask.mutate(task.id)}} disabled={task.running||deleteSnapshotTask.isPending}><Trash2/></Button></div></li>)}</ul>}
    </CardContent></Card>
    {(peers ?? []).map((peer) => { const versionMismatch = Boolean(peer.remoteVersion && localServer?.version && peer.remoteVersion !== localServer.version); return <Card key={peer.id}><CardContent className="flex flex-wrap items-center justify-between gap-3 p-4"><div className="min-w-0"><p className="flex flex-wrap items-center gap-2 text-sm font-medium"><Link2 className="size-4 text-muted-foreground" />{peer.name}<Badge variant={peer.remoteStatus === 'offline' || peer.lastError ? 'destructive' : needsAttention(peer) || versionMismatch ? 'warning' : 'success'}>{peer.remoteStatus === 'offline' ? 'offline' : peer.lastError ? 'failed' : versionMismatch ? 'version mismatch' : needsAttention(peer) ? 'stale' : 'current'}</Badge><Badge variant={peer.remoteStatus === 'online' ? 'success' : peer.remoteStatus === 'offline' ? 'destructive' : 'secondary'}>{peer.remoteStatus ?? 'checking'}</Badge></p><p className="mt-1 truncate text-xs text-muted-foreground">{peer.url} · {peer.lastSyncAt ? `last copy ${timeAgo(peer.lastSyncAt)}` : 'not replicated yet'}{peer.remoteCheckedAt ? ` · checked ${timeAgo(peer.remoteCheckedAt)}` : ''}</p>{peer.remoteVersion && <p className="mt-1 text-xs text-muted-foreground">Remote LumoNAS {peer.remoteVersion}{localServer?.version ? ` · this NAS ${localServer.version}` : ''}{peer.remoteHealth ? ` · health ${peer.remoteHealth}` : ''}</p>}{peer.lastError ? <AlertBanner className="mt-2" tone="critical" title="Last replication failed"><span className="inline-flex items-center gap-1"><TriangleAlert className="size-3" />{peer.lastError}</span></AlertBanner> : peer.remoteStatus === 'offline' ? <p className="mt-1 text-xs text-attention">The remote LumoNAS did not answer its HTTPS health check.</p> : versionMismatch ? <p className="mt-1 text-xs text-attention">NAS software versions differ. Review the peer before relying on cross-version recovery.</p> : needsAttention(peer) ? <p className="mt-1 text-xs text-attention">No successful replica in the last 7 days. Run replication and check the destination.</p> : null}</div><div className="flex shrink-0 gap-2"><Button size="sm" variant="outline" asChild><a href={peer.url} target="_blank" rel="noopener noreferrer"><ExternalLink />Open NAS</a></Button><Button size="sm" variant="outline" onClick={() => run.mutate(peer.id)} disabled={run.isPending || peer.remoteStatus === 'offline'}><Play />Replicate now</Button><Button size="sm" variant="ghost" aria-label={`Remove ${peer.name}`} className="text-destructive hover:text-destructive" onClick={() => setRemoveTarget(peer)}><Trash2 /></Button></div></CardContent></Card> })}
    {(peers?.length ?? 0) === 0 && <p className="py-6 text-center text-sm text-muted-foreground">No paired LumoNAS nodes yet.</p>}
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Pair a LumoNAS replica</DialogTitle><DialogDescription>Create the two narrow tokens on the destination NAS, then paste them here. Peer URLs must use HTTPS.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={submit}><div className="space-y-2"><Label htmlFor="peer-name">Name</Label><Input id="peer-name" value={name} onChange={(e) => setName(e.target.value)} placeholder="Parents' NAS" /></div><div className="space-y-2"><Label htmlFor="peer-url">Destination URL</Label><Input id="peer-url" value={url} onChange={(e) => setURL(e.target.value)} placeholder="https://nas.example.net" /></div><div className="space-y-2"><Label htmlFor="peer-token">Receive-only replication token</Label><Input id="peer-token" type="password" value={token} onChange={(e) => setToken(e.target.value)} autoComplete="off" /></div><div className="space-y-2"><Label htmlFor="peer-status-token">Fleet status token (recommended)</Label><Input id="peer-status-token" type="password" value={statusToken} onChange={(e) => setStatusToken(e.target.value)} autoComplete="off" /><p className="text-xs text-muted-foreground">Create a separate fleet:status token to show remote software version and health. Leave blank to use basic online/offline checks.</p></div><DialogFooter><Button type="button" variant="ghost" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" disabled={!name.trim() || !url.trim() || !token || save.isPending}>Pair NAS</Button></DialogFooter></form></DialogContent></Dialog>
    <Dialog open={removeTarget != null} onOpenChange={(next) => !next && setRemoveTarget(null)}><DialogContent><DialogHeader><DialogTitle>Remove replication peer?</DialogTitle><DialogDescription>This stops future copies to {removeTarget?.name}. Existing recovery bundles already stored on that NAS are not deleted.</DialogDescription></DialogHeader><DialogFooter><Button variant="ghost" onClick={() => setRemoveTarget(null)}>Cancel</Button><Button variant="destructive" disabled={!removeTarget || remove.isPending} onClick={() => { if (!removeTarget) return; remove.mutate(removeTarget.id, { onSuccess: () => setRemoveTarget(null) }) }}>{remove.isPending ? 'Removing…' : 'Remove peer'}</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
